### ISSUE TITLE
Custom handler for expectedOrigin and expectedRPID

### ISSUE THREAD

**Issue by Mikescops** [MasterKale/SimpleWebAuthn#102]
Hello,

As a followup of #90, when using a browser extension, having multiple origin/rpID possible was really cool but we got into facing another issue which is that some browsers like Firefox are using random IDs for their extensions that means it's impossible to maintain a hard-coded list of origins/rpID.

For instance here is the way to validate a FF origin:
```
    const originIsMozillaExtension = origin.match(
        /^moz-extension:\/\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/
    );
```

I know it's yet another addition but would you allow to have a custom function handler to validate origins and rpIDs?
Let me know if you have a better solution but I guess anyone using SWA with browser extension will face this issue.

**Comment by MasterKale** [comment]
After bootstrapping a new extension using Mozilla's "baby's first extension" tutorial I tried to find out if it's possible for an extension to discover its internal UUID. It seems it is indeed possible to get the current UUID via the [`runtime.getURL()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getURL) API:

```js
const imgURL = browser.runtime.getURL('manifest.json');
const idRegEx = /^moz-extension:\/\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/;

console.log(`extension UUID: ${idRegEx.exec(imgURL)}`);
```

![Screen Shot 2021-02-15 at 8 10 38 AM](https://user-images.githubusercontent.com/5166470/107969944-539b5180-6f65-11eb-8225-f0b16efab997.png)

Which matches with the UUID that's visible from the extensions page:

![Screen Shot 2021-02-15 at 8 03 27 AM](https://user-images.githubusercontent.com/5166470/107969317-7b3dea00-6f64-11eb-990d-d8372e8737a0.png)

Can you use this technique to get a given instance's UUID string, which you can then pass in as `rpID` for options or `expectedRPID` for verification?

**Comment by Mikescops** [comment]
So we've made some tests and we found out that the RP ID is similar to the origin. See this assertion in the [SWA debugger here](https://debugger.simplewebauthn.dev/?attestation=ewogICAgImlkIjogIkFYR2o1dDc5T2xGTzR4djdrdzcwWFNpUURsLWdNUGRQWHZxOVFtSW5YQmVPZFQ0ZGVrTm5tOFMxaXNoLVJRZEVIWV9NWDBJS1EtQ1lVcEItTHBFakpISkxWeG9xVmlJR2dJTm9nS2pwLWhHU2NGRm43a3lhSkZiclNEME9KWUNZUFlab0hHWkUwZ0JJWXNIWUhlNVJaQ0lTUmYtb3B6WXoyWjlTWG1MeEpkZEE2U1ZpQVc5cmhLWUhyQWhiUkF6TGdyTVozV1Bma0hFX3pWN2JCU3Qyam5HbVJEMUc0My1zZE1tM0tDRTA2VU1Nd3lhVEtOX3pycXdOMGVkcmZjenZvLVpIIiwKICAgICJ0eXBlIjogInB1YmxpYy1rZXkiLAogICAgInJhd0lkIjogIkFYR2o1dDc5T2xGTzR4djdrdzcwWFNpUURsLWdNUGRQWHZxOVFtSW5YQmVPZFQ0ZGVrTm5tOFMxaXNoLVJRZEVIWV9NWDBJS1EtQ1lVcEItTHBFakpISkxWeG9xVmlJR2dJTm9nS2pwLWhHU2NGRm43a3lhSkZiclNEME9KWUNZUFlab0hHWkUwZ0JJWXNIWUhlNVJaQ0lTUmYtb3B6WXoyWjlTWG1MeEpkZEE2U1ZpQVc5cmhLWUhyQWhiUkF6TGdyTVozV1Bma0hFX3pWN2JCU3Qyam5HbVJEMUc0My1zZE1tM0tDRTA2VU1Nd3lhVEtOX3pycXdOMGVkcmZjenZvLVpIIiwKICAgICJyZXNwb25zZSI6IHsKICAgICAgImNsaWVudERhdGFKU09OIjogImV5SjBlWEJsSWpvaWQyVmlZWFYwYUc0dVkzSmxZWFJsSWl3aVkyaGhiR3hsYm1kbElqb2lZVEZrWVRFMlpUZ3hZekJpWkdRd09UaGhNRFJoT1RGbU9EVXpNRGMyWWpNM09EVmhZVGt4TldabU1EZGpNV0ZqWXpJNU5HVTNZVFZrTmpNNU5EWmlZeUlzSW05eWFXZHBiaUk2SW1Ob2NtOXRaUzFsZUhSbGJuTnBiMjQ2THk5bmJtMWxZbVJsWldkdlptZG9iR3h0Yld4dVoyMWtiVzluYUd0bFluQnRaaUlzSW1OeWIzTnpUM0pwWjJsdUlqcG1ZV3h6WlgwIiwKICAgICAgImF0dGVzdGF0aW9uT2JqZWN0IjogIm8yTm1iWFJrYm05dVpXZGhkSFJUZEcxMG9HaGhkWFJvUkdGMFlWa0JSLWNidHpkZ3owaU56dkJ6TDVJQmZuOEY4dGtybWR4MnQ3WUVwUmZydGdlVFJXQXJoalN0emdBQ05iekdDbVNMQ3lYeDhGVURBTU1CY2FQbTN2MDZVVTdqR191VER2UmRLSkFPWDZBdzkwOWUtcjFDWWlkY0Y0NTFQaDE2UTJlYnhMV0t5SDVGQjBRZGo4eGZRZ3BENEpoU2tINHVrU01rY2t0WEdpcFdJZ2FBZzJpQXFPbjZFWkp3VVdmdVRKb2tWdXRJUFE0bGdKZzlobWdjWmtUU0FFaGl3ZGdkN2xGa0loSkZfNmluTmpQWm4xSmVZdkVsMTBEcEpXSUJiMnVFcGdlc0NGdEVETXVDc3huZFk5LVFjVF9OWHRzRkszYU9jYVpFUFViamY2eDB5YmNvSVRUcFF3ekRKcE1vM19PdXJBM1I1MnQ5ek8tajVrZWxBUUlESmlBQklWZ2dqaUVTbTNZN0tsUUpmNlhlVHJpWFNzUzBHdzdUY09OX3lWU1MwNDVHeUtraVdDRFcwcDU5RzFKUHZ5Rzh5aFdxbHE0dFJ3ejlWYlNmeDlramJBdTRmTHVtSnciCiAgICB9Cn0).

If you take the rpID hash it's `"e71bb73760cf488dcef0732f92017e7f05f2d92b99dc76b7b604a517ebb60793"`

Now trying to found this hash from the uuid:

```
> a = crypto.createHash('SHA256').update(Buffer.from('gnmebdeegofghllmmlngmdmoghkebpmf', 'ascii')).digest(); console.log(a.toString('hex'));
372c27c61b49497b4dd746f02ce598d4d07efe605858c05d578aae148bc3ed83

> a = crypto.createHash('SHA256').update(Buffer.from('chrome-extension://gnmebdeegofghllmmlngmdmoghkebpmf', 'ascii')).digest(); console.log(a.toString('hex'));
e71bb73760cf488dcef0732f92017e7f05f2d92b99dc76b7b604a517ebb60793
```

So in this example the RPID === origin. But what's interesting is that the parameter passed to webauthn.create was only `"gnmebdeegofghllmmlngmdmoghkebpmf"`. So that means something changed it on it's way.

And here is a interesting PR on webauthn project: https://github.com/w3c/webauthn/pull/1033 that may explain this behavior.

We also tried to pass different things to the webauthn.create but ended up with `DOMException: Public-key credentials are only available to HTTPS origin or HTTP origins that fall under 'localhost'.`.

Concerning the fact that we can get the uuid with `runtime.getURL()` it's known. But the issue is that the server is not aware of it as we put our expectedOrigin/RPID in our configuration.

I hope this helps but to be honest there is a big lack of documentation around webauthn and extensions :disappointed:

**Comment by MasterKale** [comment]
I suspect you're suffering from nuances of the CTAP2 protocol, the part of WebAuthn that dictates how the authenticator generates a response for whatever options the browser gives it.

It seems for Chrome specifically you need to pass in the full extension URI for `expectedRPID`, not just the extension's ID...this isn't the case with Firefox? Is there the added twist that the `rpIdHash` in Firefox extensions is generated from just the ID as expected?

I don't think this is related to extensions...it might save you some headache to table that investigation for now. I'm going to look at the CTAP2 part of the spec a bit closer and see if anything in there explains this. Maybe it's a browser implementation issue 🤷‍♂️

**Comment by MasterKale** [comment]
I found this part in the spec (apologies for phone posting):

![image](https://user-images.githubusercontent.com/5166470/108060784-38375180-700c-11eb-8683-4b872aae2f34.png)

> The RP ID is originally received from the client when the credential is created, and again when an assertion is generated. However, it differs from other client data in some important ways. First, unlike the client data, the RP ID of a credential does not change between operations but instead remains the same for the lifetime of that credential. Secondly, it is validated by the authenticator during the authenticatorGetAssertion operation, by verifying that the RP ID that the requested credential is scoped to exactly matches the RP ID supplied by the client.
> 
> Authenticators perform the following steps to generate an authenticator data structure:
> 
> - Hash RP ID using SHA-256 to generate the rpIdHash.

Now I'm suspecting Chrome itself will end up being the culprit, as it's responsible for passing along your `rpID` in the options you provide to its `navigator.credential` APIs.

**Comment by Mikescops** [comment]
So I made a series of tests.

For Chrome:
- Don't work when a protocol different than `https` is specified.

- Works only with rpID set with the ID of extension (like `nhnjjlokanokjhheekkcgoiblhljealo`) and then in the attestation response it was modified (by the browser? :man_shrugging: ) to `chrome-extension://nhnjjlokanokjhheekkcgoiblhljealo`.
See [example here](https://debugger.simplewebauthn.dev/?attestation=eyJpZCI6IktHMkMxQ0pzendXeW5ZdzVmWXYwdXciLCJyYXdJZCI6IktHMkMxQ0pzendXeW5ZdzVmWXYwdXciLCJyZXNwb25zZSI6eyJhdHRlc3RhdGlvbk9iamVjdCI6Im8yTm1iWFJrYm05dVpXZGhkSFJUZEcxMG9HaGhkWFJvUkdGMFlWaVVkdnphQVRhTWlQOFhEdHJjNHI4S1g4VFI1YUNTYV9TLXdRenEzS3o0Y050RkFBQUFIUUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFFQ2h0Z3RRaWJNOEZzcDJNT1gyTDlMdWxBUUlESmlBQklWZ2d1MnVZZ19mNGJUZ2lmMi1INEpKdVMyTUMySXJXTVlyazFWQ2FqYV9hdzA4aVdDQ2RfajR0ZUl6MjhzRXFkbnhkMmhBREFnSjlJeS00Qk9nZ1RSQ3NjNE1Ya2ciLCJjbGllbnREYXRhSlNPTiI6ImV5SjBlWEJsSWpvaWQyVmlZWFYwYUc0dVkzSmxZWFJsSWl3aVkyaGhiR3hsYm1kbElqb2lXVkZCZUVGSFVVRlpVVUY0UVVSWlFWcFJRVFJCUkVWQldYZEJkMEZIU1VGYVFVSnJRVVJCUVU5UlFUUkJSMFZCVFVGQk1FRkhSVUZQVVVGNFFVZFpRVTlCUVRGQlJFMUJUVUZCTTBGRVdVRlpaMEY2UVVSalFVOUJRVEZCUjBWQldWRkJOVUZFUlVGT1VVSnRRVWRaUVUxQlFUTkJSMDFCVFZGQ2FFRkhUVUZaZDBGNVFVUnJRVTVCUW14QlJHTkJXVkZCTVVGSFVVRk9aMEY2UVVSclFVNUJRVEpCUjBsQldYZEJJaXdpYjNKcFoybHVJam9pWTJoeWIyMWxMV1Y0ZEdWdWMybHZiam92TDI1b2JtcHFiRzlyWVc1dmEycG9hR1ZsYTJ0aloyOXBZbXhvYkdwbFlXeHZJaXdpWTNKdmMzTlBjbWxuYVc0aU9tWmhiSE5sZlEifSwidHlwZSI6InB1YmxpYy1rZXkiLCJjbGllbnRFeHRlbnNpb25SZXN1bHRzIjp7fX0K).

 
 For Firefox: 
 - Don't work when a protocol different than `https` is specified.

- When setting the rpID to the UUID, the ui is triggered but I was unable to validate my Yubikey nothing was happening until timeout.
![image](https://user-images.githubusercontent.com/4266283/108078579-238ba580-706e-11eb-904f-aa88b020bc88.png)
So I don't know if it works at all on Firefox or if I missed something.

**Comment by Mikescops** [comment]
I think webextensions fits in this part of the spec:
> Other specifications mimicking the WebAuthn API to enable WebAuthn public key credentials on non-Web platforms (e.g. native mobile applications), MAY define different rules for binding a caller to a Relying Party Identifier. Though, the RP ID syntaxes MUST conform to either valid domain strings or URIs [RFC3986] [URL].

https://www.w3.org/TR/webauthn/#note-pkcredscope

**Comment by Mikescops** [comment]
So here is a reply from Google team:
```
RP IDs are defined to be a domain name, but extensions don't have a domain name. In order to avoid collisions with domain names, different identifier spaces are distinguished by representing them as URLs. See this note in the spec: https://www.w3.org/TR/webauthn-2/#ref-for-webauthn-client%E2%91%A4:~:text=Other%20specifications%20mimicking%20the%20WebAuthn%20API%20to%20enable%20WebAuthn
Chrome extensions are not intended to specify an RP ID in the WebAuthn call at all although it does happen to work if you specify the extension ID.
```

**Comment by Mikescops** [comment]
Hello again,
I have opened a discussion with Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1693562
There are interesting elements to discuss.

Also I created a test extension: https://github.com/Mikescops/webauthn-extension-playground

**Comment by MasterKale** [comment]
@Mikescops Thank you for the update! Seeing WebAuthn in action in a browser extension is pretty exciting for me, even with Firefox giving you issues (and I totally approve of how you linked to the SimpleWebAuthn debugger 😛). I'll be following that Mozilla bugzilla entry you linked, here's hoping for a speedy resolution 🤞

**Comment by Mikescops** [comment]
The debugger is rich idea you had :+1: hopes we make webauthn a great standard everywhere :smile:
