### ISSUE TITLE
"list" argument must be an Array of Buffers

### ISSUE THREAD

**Issue by GagnDeep** [MasterKale/SimpleWebAuthn#110]
I was trying to use @simplewebauthn/server in cloudflare workers, but getting this error when verifying attestation

```
TypeError: "list" argument must be an Array of Buffers
    at Function.a.concat (index.js:376)
    at Object.convertCOSEtoPKCS [as default] (convertCOSEtoPKCS.js:19)
    at Object.verifyAttestationPacked [as default] (verifyPacked.js:50)
    at verifyAttestationResponse (verifyAttestationResponse.js:166)
```

Cloudflare workers provide access to most browser api's including cypto api. Is this possible to run this package in cloudflare workers with browserifying ?

**Comment by MasterKale** [comment]
@GagnDeep Can you provide an example of how you're calling `verifyAttestationResponse`, including the arguments you're feeding it?

**Comment by GagnDeep** [comment]
```javascript
async function handleVerifyAttestation({attestationRes, user, rpID, expectedOrigin}) {
    const expectedChallenge = user.currentChallenge;
    try {
      const opts = {
        credential: attestationRes,
        expectedChallenge: `${expectedChallenge}`,
        expectedOrigin,
        expectedRPID: rpID
      };

      return await verifyAttestationResponse(opts);
    } catch (error) {
      throw error;
    }
  }
```
Here `attestationRes` will be the response of calling `startAttestation` in browser, similar to in example.

Here's a codesanbox [link](https://codesandbox.io/s/great-goldwasser-23gss?file=/App.svelte). Worker i cannot share easily but running it here provides similar enviroment of what i have in worker. And here also it throws same error `"list" argument must be an Array of Buffers`

When running this example just don't use the embedded browser. Click on open in new tab and open console to see that error

**Comment by MasterKale** [comment]
Thank you for providing the CodeSandbox. It appears this is an issue with attestation statement verification. The following direct attestations generate that error:

FIDO-U2F: [SimpleWebAuthn debugger link](https://debugger.simplewebauthn.dev/?attestation=ewogICJpZCI6ICIwd3MxRDNFQk9ZNEFfcXdBRUJPQjRJQXMweGItMWMxbWxldGV6N093TV9vc1BNQTIta09ZUlhlMTg1MEoyVmg3bkh2RGI2ZHl2Zjhkcm1Yb3pObGxfQSIsCiAgInJhd0lkIjogIjB3czFEM0VCT1k0QV9xd0FFQk9CNElBczB4Yi0xYzFtbGV0ZXo3T3dNX29zUE1BMi1rT1lSWGUxODUwSjJWaDduSHZEYjZkeXZmOGRybVhvek5sbF9BIiwKICAicmVzcG9uc2UiOiB7CiAgICAiYXR0ZXN0YXRpb25PYmplY3QiOiAibzJObWJYUm9abWxrYnkxMU1tWm5ZWFIwVTNSdGRLSmpjMmxuV0Vjd1JRSWdPejYyX1VkNnF5c2JMOXdmS3lrVHQ3d2pWN1g5Q0JBYzMzSjBrZlp5aklFQ0lRRFgtaDlmOWs1Y2lETm1rdkl5SER6eXFRU00tZlVxUjI4eklod2hxLUpnbm1ONE5XT0JXUUxCTUlJQ3ZUQ0NBYVdnQXdJQkFnSUVLdWRpWXpBTkJna3Foa2lHOXcwQkFRc0ZBREF1TVN3d0tnWURWUVFERXlOWmRXSnBZMjhnVlRKR0lGSnZiM1FnUTBFZ1UyVnlhV0ZzSURRMU56SXdNRFl6TVRBZ0Z3MHhOREE0TURFd01EQXdNREJhR0E4eU1EVXdNRGt3TkRBd01EQXdNRm93YmpFTE1Ba0dBMVVFQmhNQ1UwVXhFakFRQmdOVkJBb01DVmwxWW1samJ5QkJRakVpTUNBR0ExVUVDd3daUVhWMGFHVnVkR2xqWVhSdmNpQkJkSFJsYzNSaGRHbHZiakVuTUNVR0ExVUVBd3dlV1hWaWFXTnZJRlV5UmlCRlJTQlRaWEpwWVd3Z056RTVPREEzTURjMU1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRUtnT0dYbUJEMlo0Ul94Q3FKVlJYaEw4SnI0NXJIanN5RnlraGIxVVNHb3paRU5PWjNjZG92ZjVLZThmajJyeGk1dEpHbl9Wblc0XzZpUXpLZElhZVA2TnNNR293SWdZSkt3WUJCQUdDeEFvQ0JCVXhMak11Tmk0eExqUXVNUzQwTVRRNE1pNHhMakV3RXdZTEt3WUJCQUdDNVJ3Q0FRRUVCQU1DQkRBd0lRWUxLd1lCQkFHQzVSd0JBUVFFRWdRUWJVUzZtX2JzTGttNU1BeVA2U0RMY3pBTUJnTlZIUk1CQWY4RUFqQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJ5VjlBODNNUGhGV21Fa05iNER2bGJVd2NqYzlubVJ6SmpLeEhjM0hlSzdHdlZrbTBINFh1Y1ZEQjRqZU12VGtlMFdIYl9qRlVpQXB2cE9IaDVWeU14NXlkd0ZvS0tjUnM1eDBfV3dTV0wwZVRaNVdiVmNIa0RSOXBTTmNBX0RfNUFzVUtPQmNicEY1bmtkVlJ4YVFIdXVJdXdWNGsxaUsySXF0TU5jVTh2TDZ3MjFVMjYxeENjV3dKNnNNcTR6elZPOFFDS0NRaHNvSWFXcnd6ODI4R0RtUHpmQWpGc0ppTEpYdVlpdmRIQUNrZUo1S0hNdDBtalZMcGZKMkJDTUw3X3JnYm12d0w3d0JXODBWSGZOZGNLbUtqa0xjcEVpUHp3Y1FRaGlOX3FIVjkwdC1wNGl5cjV4UlNwdXJsUDV6aWMyaGxSa0xLeE1IMl9rUmpocVNuNGFHRjFkR2hFWVhSaFdNVEdkZXF3YXR6SnQ5dDBmQldiQ1IyMXlHdnAtNHZXTWxDNEIwTnJuNGdFRDBFQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQkEwd3MxRDNFQk9ZNEFfcXdBRUJPQjRJQXMweGItMWMxbWxldGV6N093TV9vc1BNQTIta09ZUlhlMTg1MEoyVmg3bkh2RGI2ZHl2Zjhkcm1Yb3pObGxfS1VCQWdNbUlBRWhXQ0J1Rzd3V2dRTm1mOXlnRWgwSEV1TUFVcnI2VnptU2RKTmNmU3h2YXRHRHBpSllJTm54YWdOaEhiZE9Kei14TzUyWldkT3JQbEp4NTFSU0FLWGFfaTBwREtTRSIsCiAgICAiY2xpZW50RGF0YUpTT04iOiAiZXlKamFHRnNiR1Z1WjJVaU9pSmtXbmhwYW1OYVVYVlhjM0ZXUlhCUE5GZE1URmRRZVcxd2RVMU1jbFJzVkd4VlYwTnZTVkF3ZFZwQklpd2lZMnhwWlc1MFJYaDBaVzV6YVc5dWN5STZlMzBzSW1oaGMyaEJiR2R2Y21sMGFHMGlPaUpUU0VFdE1qVTJJaXdpYjNKcFoybHVJam9pYUhSMGNITTZMeTluTm5CMVl5NWpjMkl1WVhCd0lpd2lkSGx3WlNJNkluZGxZbUYxZEdodUxtTnlaV0YwWlNKOSIKICB9LAogICJ0eXBlIjogInB1YmxpYy1rZXkiLAogICJjbGllbnRFeHRlbnNpb25SZXN1bHRzIjoge30KfQ)

Packed: [SimpleWebAuthn debugger link](https://debugger.simplewebauthn.dev/?attestation=ewogICAgImlkIjogImVsTjcweWl5Z0hhRTk3QXVpTXdHbm16aXhWN2p4MlFmTnpsWTEzN3Myd1lCWFhrLUk2dzM2V1FKQjkySDlwcDZnM1ppeUFNZ1lVQjIwd0NOSVhxX29BIiwKICAgICJyYXdJZCI6ICJlbE43MHlpeWdIYUU5N0F1aU13R25teml4VjdqeDJRZk56bFkxMzdzMndZQlhYay1JNnczNldRSkI5Mkg5cHA2ZzNaaXlBTWdZVUIyMHdDTklYcV9vQSIsCiAgICAicmVzcG9uc2UiOiB7CiAgICAgICAgImF0dGVzdGF0aW9uT2JqZWN0IjogIm8yTm1iWFJtY0dGamEyVmtaMkYwZEZOMGJYU2pZMkZzWnlaamMybG5XRWd3UmdJaEFQTWRpV0Vvd3l3MFNGZ2hSTWJaSUY4NlBPem93UTVIc2tybVMyUmwtanVTQWlFQW9veWNyZE5ZX3owcjZIZkU5X2VQTjdQRTNyOUh2NmpVTlVySl81SFh6VFpqZURWamdWa0N3VENDQXIwd2dnR2xvQU1DQVFJQ0JDcm5ZbU13RFFZSktvWklodmNOQVFFTEJRQXdMakVzTUNvR0ExVUVBeE1qV1hWaWFXTnZJRlV5UmlCU2IyOTBJRU5CSUZObGNtbGhiQ0EwTlRjeU1EQTJNekV3SUJjTk1UUXdPREF4TURBd01EQXdXaGdQTWpBMU1EQTVNRFF3TURBd01EQmFNRzR4Q3pBSkJnTlZCQVlUQWxORk1SSXdFQVlEVlFRS0RBbFpkV0pwWTI4Z1FVSXhJakFnQmdOVkJBc01HVUYxZEdobGJuUnBZMkYwYjNJZ1FYUjBaWE4wWVhScGIyNHhKekFsQmdOVkJBTU1IbGwxWW1samJ5QlZNa1lnUlVVZ1UyVnlhV0ZzSURjeE9UZ3dOekEzTlRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkNvRGhsNWdROW1lRWY4UXFpVlVWNFNfQ2EtT2F4NDdNaGNwSVc5VkVocU0yUkRUbWQzSGFMMy1TbnZINDlxOFl1YlNScF8xWjF1UC1va015blNHbmotamJEQnFNQ0lHQ1NzR0FRUUJnc1FLQWdRVk1TNHpMall1TVM0MExqRXVOREUwT0RJdU1TNHhNQk1HQ3lzR0FRUUJndVVjQWdFQkJBUURBZ1F3TUNFR0N5c0dBUVFCZ3VVY0FRRUVCQklFRUcxRXVwdjI3QzVKdVRBTWota2d5M013REFZRFZSMFRBUUhfQkFJd0FEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFjbGZRUE56RDRSVnBoSkRXLUE3NVcxTUhJM1BaNWtjeVl5c1IzTngzaXV4cjFaSnRCLUY3bkZRd2VJM2pMMDVIdEZoMl80eFZJZ0tiNlRoNGVWY2pNZWNuY0JhQ2luRWJPY2RQMXNFbGk5SGsyZVZtMVhCNUEwZmFValhBUHdfLVFMRkNqZ1hHNlJlWjVIVlVjV2tCN3JpTHNGZUpOWWl0aUtyVERYRlBMeS1zTnRWTnV0Y1FuRnNDZXJES3VNODFUdkVBaWdrSWJLQ0dscThNX052Qmc1ajgzd0l4YkNZaXlWN21JcjNSd0FwSGllU2h6TGRKbzFTNlh5ZGdRakMtXzY0RzVyOEMtOEFWdk5GUjN6WFhDcGlvNUMzS1JJajg4SEVFSVlqZjZoMWZkTGZxZUlzcS1jVVVxYnE1VC1jNG5Ob1pVWkN5c1RCOXY1RVk0YWtwLUdoaGRYUm9SR0YwWVZqRXhuWHFzR3JjeWJmYmRId1Ztd2tkdGNocjZmdUwxakpRdUFkRGE1LUlCQTlCQUFBQUgyMUV1cHYyN0M1SnVUQU1qLWtneTNNQVFIcFRlOU1vc29CMmhQZXdMb2pNQnA1czRzVmU0OGRrSHpjNVdOZC03TnNHQVYxNVBpT3NOLWxrQ1FmZGhfYWFlb04yWXNnRElHRkFkdE1BalNGNnY2Q2xBUUlESmlBQklWZ2c4QnBwOC1WOWZZOS1TNGFjTUpFeW9kQnFmRUtDY1pNRlo2ekFJbS1lNFNBaVdDRGRXdHBpd2FCTUQ1OENZN2ljbWd1bk9pWVE4RnozOGtoS0EwaVdLaUktb1EiLAogICAgICAgICJjbGllbnREYXRhSlNPTiI6ICJleUowZVhCbElqb2lkMlZpWVhWMGFHNHVZM0psWVhSbElpd2lZMmhoYkd4bGJtZGxJam9pUW00dGVVd3hOMk5tUTFONk4xZGlaMHhXUTBzd2NrcE9kM2xZWlZoNU5YVllUMmcyYTNkVFNXeFRXU0lzSW05eWFXZHBiaUk2SW1oMGRIQnpPaTh2Wnpad2RXTXVZM05pTG1Gd2NDSXNJbU55YjNOelQzSnBaMmx1SWpwbVlXeHpaWDAiCiAgICB9LAogICAgInR5cGUiOiAicHVibGljLWtleSIsCiAgICAiY2xpZW50RXh0ZW5zaW9uUmVzdWx0cyI6IHt9LAogICAgInRyYW5zcG9ydHMiOiBbCiAgICAgICAgIm5mYyIsCiAgICAgICAgInVzYiIKICAgIF0KfQ)

I'll dig into this and report back :)

**Comment by MasterKale** [comment]
@GagnDeep I ran those two attestation responses through unit testing and they verified fine for me. Upon close examination of that CodeSandbox example, it appears to me that it's polyfilling enough of Node's APIs to _mostly enable execution of **@simplewebauthn/server** in the browser._ I hope you'll understand when I say that that's not a supported use case of that package - it's Node or nothing 😂

As for your Cloudflare Worker issue, I imagine your problem there is that Cloudflare Workers execute JavaScript in an environment that is more similar to browsers than Node. CF Workers and Node are both V8-powered, but offer separate collections of APIs and so are not equivalent runtime environments. The issue with `"list" argument must be an Array of Buffers` is probably somehow related to the fact that `Buffer` values, which **@simplewebauthn/server** make extensive use of, are a NodeJS data type that browser-like runtime environments lack native support for.

[Browser polyfills to support NodeJS Buffers exist](https://github.com/feross/buffer), so there's a chance you _could_ get something to work, but at this time this is not a supported use case of **@simplewebauthn/server**.
