### ISSUE TITLE
Support user verification

### ISSUE THREAD

**Issue by P4sca1** [MasterKale/SimpleWebAuthn#12]
The default value of user verification is "preferred". Chromium shows the following warning when using the default: https://chromium.googlesource.com/chromium/src/+/master/content/browser/webauth/uv_preferred.md
We should make it possible to pass a custom user verification flag to `generateAssertionOptions` and `generateAtestationOptions`. By default `undefined` should be used to let the browser decide on the default (which is `preferred` at the moment).

It would be great to add a description to the parameter stating that:
* UV should be set to `discouraged` when Webauthn is used as a multi factor.
* UV should be set to `preferred` or `required` when Webauthn is used as a stand alone passwordless (or even usernameless) flow.

**Comment by P4sca1** [comment]
`discouraged` is recommended for better UX when Webauthn is used as a multi factor, because otherwise instead of 2 factor authenticator, you have 3 factor authentication which leads bad UX and is generally considered overkill:
1) Enter username and password
2) Use Webauthn authenticator
3) Authenticate to your webauthn authenticator.

Of course when not using user verification, you are vulnerable if an attacker has both username and password and your physical key, but that is a highly unlikely scenario. Also when your key is lost, you should just remove it from your account.

**Comment by herrjemand** [comment]
Correct @P4sca1

**Comment by MasterKale** [comment]
This is a great suggestion, and looks pretty straight forward to implement. I'll aim to add this in once the project rename is complete :)

**Comment by MasterKale** [comment]
I've added support for specifying an assertion's `userVerification` (and attestation's `authenticatorSelection` too!) with #17:

**userVerification:**

![Screen Shot 2020-05-26 at 11 35 20 PM](https://user-images.githubusercontent.com/5166470/82985919-c0228a80-9fa9-11ea-9831-96cece80b578.png)

**authenticatorSelection:**

![Screen Shot 2020-05-26 at 11 35 07 PM](https://user-images.githubusercontent.com/5166470/82985958-cdd81000-9fa9-11ea-950a-dff413b42806.png)
