### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by timstrasser** [MasterKale/SimpleWebAuthn#133]
I just updated the '@simplewebauthn/browser' dependency in my NUXT project (from ^3.0.0 to ^3.1.0) and now the pages that require startAttestation from the @simplewebauthn/browser package no longer render.

I get the following error:
webpack:/external "@simplewebauthn/browser"
Missing stack framesJS 
Object.@simplewebauthn/browser@1:

(https://prnt.sc/17aah2p)

I don't know how to further debug this error. Let me know if I can provide more information on this error.

**Comment by akanass** [comment]
@timstrasser Did you check the `README` because in the latest version, `main` version is in `ES2018` and you have to transpile it by yourself with your bundle system if you want a lower support.

**Comment by timstrasser** [comment]
No, indeed I did not check the README. Can you give me any information on how to do this? Or on how to configure NUXT to do this?

**Comment by akanass** [comment]
@timstrasser as it's explained in the official [documentation](https://nuxtjs.org/docs/2.x/directory-structure/nuxt-config#build) you can extend `webpack` config to transpile `ESM` to `CJS` by adding some plugin.

**Comment by timstrasser** [comment]
Yes, I found it fox NUXT here (https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build#transpile). :)

Thanks for the quick response!
