### ISSUE TITLE
Update MetadataService to support MDS v3

### ISSUE THREAD

**Issue by MaKleSoft** [MasterKale/SimpleWebAuthn#143]
Looks like MDS v2 is deprecated (or at least it's no longer possible to obtain an access token). The good news is that v3 seems to be a lot simpler to implement (no access token required, all data can be downloaded in a single file). Maybe a good addition to the v4 milestone?

**Comment by MasterKale** [comment]
The fire has been lit! Thank you!

This morning I pushed up a branch with some initial work I'd started a month or so ago - PR #144 will capture the work of refactoring `MetadataService` to use v3 of MDS and its new data structures.

**Comment by MaKleSoft** [comment]
Haha well I would've been surprised if this hadn't been already on your radar 😁. Thanks for the prompt response!

**Comment by MasterKale** [comment]
PR #144 has been merged with full support for MDS v3. Note that this _replaces_ MDSv2 support completely. There are breaking changes to how MetadataService is initialized too - please take a look at the PR description for a list of changes if you use non-FIDO MDS URLs (or consult the CHANGELOG when I release v4.0.0)

**Comment by MasterKale** [comment]
Er, I'll leave this open until v4.0.0 actually releases 😅

**Comment by MasterKale** [comment]
This issue has been resolved in **v4.0.0**! Please see the [changelog](https://github.com/MasterKale/SimpleWebAuthn/releases/tag/v4.0.0) and [take a peek at the updated `MetadataService` docs](https://simplewebauthn.dev/docs/packages/server#metadataservice) to see what's changed while bringing support for FIDO Alliance Metadata Service v3.
