### ISSUE TITLE
Add "supportsPlatformAuthenticator" helper function

### ISSUE THREAD

**Issue by MaKleSoft** [MasterKale/SimpleWebAuthn#150]
Just a suggestion and definitely not mission-critical, but I thought that for completeness' sake, why not add 
 a `supportsPlatformAuthenticator` helper function along `supportsWebauthn`? It would basically just be a wrapper around [PublicKeyCredential::isUserVerifyingPlatformAuthenticatorAvailable]( https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/isUserVerifyingPlatformAuthenticatorAvailable).

**Comment by MasterKale** [comment]
That's an interesting suggestion. I try not to add _too_ many layers of abstraction to things, and so at first glance I'd not be eager to have such a simple wrapper be a part of this...

But maybe it's actually a good idea? One thing that comes to mind in support of your suggestion is that adding such a method would make SimpleWebAuthn _the_ abstraction devs bother committing to memory. If they're already choosing to go with an abstraction like this library then why make them mentally juggle which capabilities are part of the library and which require them to fall back to native API methods?

Thank you for encouraging me to give this some thought. I'm going to sleep on this and then come back to your proposal tomorrow.

**Comment by MaKleSoft** [comment]
> But maybe it's actually a good idea? One thing that comes to mind in support of your suggestion is that adding such a method would make SimpleWebAuthn the abstraction devs bother committing to memory. If they're already choosing to go with an abstraction like this library then why make them mentally juggle which capabilities are part of the library and which require them to fall back to native API methods?

Exactly. In my projects I maintain an abstraction layer around everything external anyway (including SimpleWebauthn) so for me it does not really matter but for most users this would definitely be a plus.

Another thing to consider is *discoverability*. Many devs adopting this library are likely only getting started working with WebAuthn so they might not be aware of all the capabilities yet. `isUserVerifyingPlatformAuthenticatorAvailable` is actually a good example for this, as I was looking for exactly this type of check and the first thing I did was look through the SimpleWebAuthn documentation to if there was something like this 😄. I then had to dig through MDN to find this native method with an extremely convoluted name.

**Comment by MasterKale** [comment]
> Another thing to consider is _discoverability_. Many devs adopting this library are likely only getting started working with WebAuthn so they might not be aware of all the capabilities yet. `isUserVerifyingPlatformAuthenticatorAvailable` is actually a good example for this, as I was looking for exactly this type of check and the first thing I did was look through the SimpleWebAuthn documentation to if there was something like this 😄. I then had to dig through MDN to find this native method with an extremely convoluted name.

This seals the deal, I'll add in such a method. The native API names have always bothered me, they're too verbose! I might as well use SimpleWebAuthn as a vehicle to help ameliorate some more challenges of working with the native API.

I'll earmark this for the 4.0 release 💪

**Comment by MaKleSoft** [comment]
Awesome! Yeah the native api is ... an acquired taste ... which is why this project is such a godsend! I'm already calling it "BetterWebAuthn" in my head 😉

**Comment by MasterKale** [comment]
Done and done. The new `platformAuthenticatorIsAvailable()` method will be available in **@simplewebauthn/browser** when v4.0 launches.

And it's unrelated to this issue but I also took this time of breaking API changes to rename `supportsWebAuthn()` to `browserSupportsWebAuthn()` to try and make things even simpler to use vis-a-vis plainly obvious indicators of what the method is actually telling you with its return.

Change for change's sake? _I think not_

**Comment by MasterKale** [comment]
This issue has been resolved in **v4.0.0**! Please see the [changelog](https://github.com/MasterKale/SimpleWebAuthn/releases/tag/v4.0.0) and [check out the docs](https://simplewebauthn.dev/docs/packages/browser#platformauthenticatorisavailable) for this new method :v:
