### ISSUE TITLE
Idea: Add new helper methods for MFA, PWL, and Usernameless registration and authentication

### ISSUE THREAD

**Issue by MasterKale** [MasterKale/SimpleWebAuthn#160]
SimpleWebAuthn already makes interacting with the WebAuthn library fairly painless, but can I take things one step further? The thought occurred to me that I might be able to offer a higher-level abstraction to the registration and authentication options generation and response verification methods. These abstractions would set combinations of options appropriate for use of WebAuthn for MFA, Passwordless, and Usernameless "modes", with minimal arguments to specify things like `allowCredentials`:

**Registration**

- `getMFARegistrationOptions()`
- `getPWLRegistrationOptions()`
- `getUNLRegistrationOptions()` (UNL -> "Usernameless", you heard it here first! 😅)

- `verifyMFARegistrationResponse()`
- `verifyPWLRegistrationResponse()`
- `verifyUNLRegistrationResponse()`

**Authentication**

- `getMFAAuthenticationOptions()`
- `getPWLAuthenticationOptions()`
- `getUNLAuthenticationOptions()`

- `verifyMFAAuthenticationResponse()`
- `verifyPWLAuthenticationResponse()`
- `verifyUNLAuthenticationResponse()`

Or maybe a new, optional `mode` argument on the existing methods that you specify as `"mfa" | "pwl" | "unl"`? That might actually be cleaner 🤔 

In any case the idea is, there are certain options you _must_ set if you want to, for example, leverage WebAuthn for Passwordless login. Without digging into the docs, though, you might not think to set them. I think there's a chance here to help devs even further by offering a quick and easy way to generate appropriate options and verify responses that will help ensure secure authentication for all use cases.

**Comment by JayHelton** [comment]
Before you ask, yes im subscriabed to the repo when new issues are update. 😆 

I like the idea of having abstractions between resident keys and non resident keys using a terminology that fits the UX. I am not confident in that abstraction being MFA / PWDL, or UNL.  What is the different between PWDL versus MFA in terms of the webauthn impl details? Off the top of my head, I cant think of any. That might change my opinion though.

In general, i prefer method abstractions over parametered abstractions, like the mode argument proposal. Then again, Im biased towards a "functional" approach over imperitive.

**Comment by MaKleSoft** [comment]
That sounds like a great idea! I think one of the main hurdles for many devs trying to adopt WebAuthn is understanding all the different use cases and how to implement them. Heck, I still haven't fully grasped how "passwordless" or "usernameless" are supposed to work in practice. I think descriptive APIs like the ones you're suggesting are a great way to guide developers towards the solution they're looking for and help avoiding many pitfalls and frustrations when adopting a new technology.

**Comment by MaKleSoft** [comment]
Oh, and I vote for the `mode` argument instead of a ton of different functions. Just my preference though.

**Comment by MasterKale** [comment]
> I like the idea of having abstractions between resident keys and non resident keys using a terminology that fits the UX. I am not confident in that abstraction being MFA / PWDL, or UNL. What is the different between PWDL versus MFA in terms of the webauthn impl details? Off the top of my head, I cant think of any. That might change my opinion though.

One of the key differences between MFA and PWL modes is that a passwordless implementation of WebAuthn _must_ require user verification for it to be true multi-factor authentication. In MFA mode the user can simply pass a User Presence check since they've provided "something you know" with the username+password they entered beforehand.

If I went with the `"mode"` argument, would it make sense for that to overwrite options the dev might otherwise set that would conflict with flags the `"mode"` argument would enforce? In my mind it would, I'd just need to communicate that in the docs. But maybe that's too much "magic"?

**Comment by MaKleSoft** [comment]
> If I went with the "mode" argument, would it make sense for that to overwrite options the dev might otherwise set that would conflict with flags the "mode" argument would enforce? In my mind it would, I'd just need to communicate that in the docs. But maybe that's too much "magic"?

I would not override, but throw an error or at least give a clear warning. You could probably even add type guards so such a mistake would show up in their editor right away (if they are using typescript).

**Comment by MasterKale** [comment]
I think I've identified a way forward for this feature:

<img width="302" alt="Screen Shot 2021-09-21 at 10 17 45 AM" src="https://user-images.githubusercontent.com/5166470/134198753-b00c8591-a887-4029-8f66-880e869d2049.png">

I'll set up TS to error out on invalid options, and then warn at runtime if invalid options are set for devs using the library in a JS project.

**Comment by JayHelton** [comment]
> > I like the idea of having abstractions between resident keys and non resident keys using a terminology that fits the UX. I am not confident in that abstraction being MFA / PWDL, or UNL. What is the different between PWDL versus MFA in terms of the webauthn impl details? Off the top of my head, I cant think of any. That might change my opinion though.
> 
> One of the key differences between MFA and PWL modes is that a passwordless implementation of WebAuthn _must_ require user verification for it to be true multi-factor authentication in one authenticator interaction. In MFA mode the user can simply pass a User Presence check since they've provided "something you know" with the username+password they entered beforehand.
> 
> If I went with the `"mode"` argument, would it make sense for that to overwrite options the dev might otherwise set that would conflict with flags the `"mode"` argument would enforce? In my mind it would, I'd just need to communicate that in the docs. But maybe that's too much "magic"?

I get it, but i have found inconsistencies for when requiring UV isnt enforced on keys if the pin is not set up. I cant say if those issues still exist in browser + OS combos. You would want to make sure that the error returned from the server on the missing UV is really clear for users of the lib and how it relates to an MFA "mode".

In addition, having a "mode" parameter feels very similar to the parameters using in cryptographic algorithms. It feels a little weird to imply there are different modes of operation in the generation of webauthn options, as opposed to just different parameters being specified or enforced.

Im on board with what you think would be the best UX, but I would still thumbs down a mode parameter.

**Comment by MasterKale** [comment]
I created #171 as a draft of how I might offer up opinionated versions of the four primary registration and authentication methods. Let me know what you think, I'll be mulling these over for the next few days.

**Comment by MasterKale** [comment]
The WebAuthn ecosystem has gone in an unexpected direction since I originally created this issue, namely with the upcoming debut of "passkeys", or "multi-device credentials" backed up/synced between devices using a platform authenticator vendor's respective cloud, in the consumer space.

In light of this new aspect of the API I can't help but think of any effort to abstract WebAuthn further, even more than SimpleWebAuthn, as something that would be best implemented as an add-on to popular frameworks like Express, Next.js, etc...

That is, I see it more prudent to encourage the creation of, say, an `express-passkey` package that defines Express-compatible request handlers to generate and validate options using SimpleWebAuthn. That package would be responsible for controlling how SimpleWebAuthn gets called specifically for enabling support for passkeys (i.e. requiring user verification during registration and auth, leaving `allowCredentials` empty, etc...) 

I, meanwhile, would continue to maintain SimpleWebAuthn as an abstraction of the WebAuthn spec itself with no other framework-specific abstractions to distract from my efforts to make the API simple to use. And in lieu of a PR like #171 I could instead augment the [docs site](https://simplewebauthn.dev/docs/) with guidance on what options to set for a given mode (e.g. "mfa", "passwordless", and "passkeys") to help library maintainers identify what to set when they're building such integration libraries.

Yeah, that sounds like a good plan 🤔

**Comment by MasterKale** [comment]
I've closed out PR #171 but will leave this issue open so I remember to update the docs.

**Comment by MasterKale** [comment]
Superseded by #264
