### ISSUE TITLE
Support the 'mediation' credential request option 

### ISSUE THREAD

**Issue by Manduro** [MasterKale/SimpleWebAuthn#209]
Right now the browser's `startAuthentication` method only passes the `publicKey` option to `navigator.credentials.get`: https://github.com/MasterKale/SimpleWebAuthn/blob/5ea1b6834b540dad6f733011556989adc66e569e/packages/browser/src/methods/startAuthentication.ts#L40

Besides the `publicKey` option, I'd like to pass the `mediation` option which is documented here: https://w3c.github.io/webappsec-credential-management/#enumdef-credentialmediationrequirement

Especially the `conditional` value will be useful as it enables browsers to present an autofill option in a login form. See https://github.com/w3c/webauthn/wiki/Explainer:-WebAuthn-Conditional-UI. Safari 16 might be the first to support this to autofill passkeys. Some info about this is available here: https://developer.apple.com/videos/play/wwdc2022/10092/?time=1036

**Comment by MasterKale** [comment]
Thanks for opening this, @Manduro. I've known about conditional UI for quite a while now, but until WWDC it still felt like something being incubated in Chrome Canacry. The demonstration of support for it in macOS Ventura established an actual deadline for anything that'd support it. As such I'm now going to prioritize adding support for it.

**Comment by MasterKale** [comment]
I've made some progress on this the last couple of days 👀 

**Chrome Canary 105:**

<img width="364" alt="Screen Shot 2022-06-16 at 10 58 20 PM" src="https://user-images.githubusercontent.com/5166470/174412791-f2684027-365c-46f2-b1fa-b05a3a391617.png">

**Safari in macOS Ventura Beta:**

![Screen Shot 2022-06-17 at 4 18 17 PM](https://user-images.githubusercontent.com/5166470/174412815-03385b1f-248e-4d5e-9b41-ef4fcf56ef36.png)

I think I've got a good idea of how I want to support this feature within **@simplewebauthn/browser**

**Comment by MasterKale** [comment]
Conditional UI is now supported in **@simplewebauthn/browser@5.3.0**. I went with "browser autofill" as a simpler way of communicating what "Conditional UI" gets you.

I've added docs as well to show how to use it:

https://simplewebauthn.dev/docs/packages/browser/#browser-autofill-aka-conditional-ui
