### ISSUE TITLE
Add link to docs

### ISSUE THREAD

**Issue by P4sca1** [MasterKale/SimpleWebAuthn#23]
At the moment there is no link to the documentation. I would add it as a website in the git description and also in the README.

**Comment by MasterKale** [comment]
Thank you for pointing this out. I’ve already linked to the docs in the browser and server READMEs specifically, but I agree it needs to be mentioned in the main README too.

**Comment by MasterKale** [comment]
The new official docs URL, https://docs.simplewebauthn.dev/, has been added to the root README for easier reference.

I've also added the new project homepage URL, https://simplewebauthn.dev/, to the Github description. The new homepage features links to the packages on NPM, a link to the API docs, and a link to this repo.
