### ISSUE TITLE
Error: Unexpected authentication response challenge token", expected "null"

### ISSUE THREAD

**Issue by rj-david** [MasterKale/SimpleWebAuthn#233]
Getting this error from our logs. Not sure if this is a bug or there is something wrong wherein the expected token is "null"
```
Error: Unexpected authentication response challenge token", expected "null"
    at verifyAuthenticationResponse (/home/bountee/bundle/programs/server/npm/node_modules/@simplewebauthn/server/dist/authentication/verifyAuthenticationResponse.js:62:15
```

**Comment by MasterKale** [comment]
What is the value of `expectedChallenge` you're passing to that method? Some example code will help me help you.

**Comment by rj-david** [comment]
Ah, got it. Need to figure out why the value being passed is null. Thanks
