### ISSUE TITLE
@simplewebauthn/browser doesn't respect excludeCredentials

### ISSUE THREAD

**Issue by chrisyalamov** [MasterKale/SimpleWebAuthn#240]
I'm pretty new to WebAuthn, so I may have got this wrong but to my understanding, by providing the populated `excludeCredentials` object, the client would not issue a new credential if one already exists on the same authenticator. My application returns a registration options object which contains `excludeCredentials`:

```
// ...
"excludeCredentials": [
        {
            "type": "public-key",
            "id": "rMyK_5Nroqc25QB4piUgIRKG4v4"
        }
    ],
// ...
```

however, `startRegistration()` still produces another credential. When storing the credential in my database, I base64url.encode its ID and then return that string when producing registrationOptions.

Am I doing something wrong, or could this be an issue with the library— any help would be appreciated 😅

**Comment by MasterKale** [comment]
Which authenticator are you working with? If you can, can you set a breakpoint on your front end code and make sure the credentials are present when SimpleWebAuthn calls `navigator.credentials.create()`? `startRegistration()` doesn't omit `excludeCredentials` for any reason so I'm thinking this is going to be an authenticator quirk you're up against.

**Comment by chrisyalamov** [comment]
I'll be honest, I'm not sure on which script to set a breakpoint— I've had a look around devtools/sources/scripts, but can't find much. I'm using TouchID on macOS in Safari. I've just tried with Safari on iOS but that doesn't even seem to bring up the prompt.

**Comment by MasterKale** [comment]
> I'm using TouchID on macOS in Safari.

I just tested this out myself and Safari seems to simply ignore entries in `excludeCredentials`; I was able to successfully register Touch ID twice in a row despite the first registration's credential ID appearing in `excludeCredentials` in the second registration.

Your code is probably fine. In this case it's just a reality of WebAuthn: there are many active players to be mindful of, including authenticator and browser vendors, and "quirks" like this are things to be aware of as you decide to move forward with this technology 😅

**Comment by MasterKale** [comment]
@chrisyalamov I'm going to close out this issue. If in the future you believe this is still legitimate then please feel free to reopen with code samples demonstrating the issue.

**Comment by thobson** [comment]
Please see [this thread](https://developer.apple.com/forums/thread/723312) on the apple developer forums
