### ISSUE TITLE
Do not check algorithm in specific case.

### ISSUE THREAD

**Issue by lightpurple** [MasterKale/SimpleWebAuthn#248]
We developed Server using simpleWebAuthn(5.4.2) library. Test by FIDO Conformance Tools 1.7.2

And I found that library no algorithm check when the fmt value is 'packed' and the x5c value exists.

So there are successful cases even if the algorithm value not allowed in the fido2. ex) `alg = -42`

<img width="718" alt="image" src="https://user-images.githubusercontent.com/58844618/184306251-1f749847-c78d-4c6f-a22b-6ae33d2f221b.png">

Can you give some suggestions to solve this?

**Comment by MasterKale** [comment]
Thanks for reporting this, I have a fix for it out in #251. I'll merge it later today and release this with the fix for #247.

**Comment by MasterKale** [comment]
The fix for this is now available in **@simplewebauthn/server@5.4.4**.
