### ISSUE TITLE
Proposal: Passkey-specific registration and authentication methods

### ISSUE THREAD

**Issue by MasterKale** [MasterKale/SimpleWebAuthn#264]
With passkeys on the horizon I thought it might be time to take another stab at #160, this time focusing only on "passkey" (a.k.a. usernameless) registration and authentication.

What would options generation and response verification methods look like if I thought only about what options should be passed to `navigator.credentials.create()` and `navigator.credentials.get()`?

The current idea in my head is to offer a new "`@simplewebauthn/server/passkeys`" import path that let you import all the usual methods by the same names, but with slightly reduced options since many of the choices can be made for you.

Consider this passkey version of `generateRegistrationOptions()`:

![Screen Shot 2022-08-23 at 8 53 38 AM](https://user-images.githubusercontent.com/5166470/186204630-3f136cfa-0a8a-4078-93c9-05f7a58fc651.png)

These few arguments would be augmented with opinionated choices for the other arguments you'd normally have to know to specify:

```ts
import {
  GenerateRegistrationOptionsOpts,
  generateRegistrationOptions as _generateRegistrationOptions
} from '../registration/generateRegistrationOptions';

export function generateRegistrationOptions(options: {
  rpID: string,
  rpName: string,
  userID: string,
  userName: string,
  authenticatorAttachment?: AuthenticatorAttachment,
  excludeCredentials?: PublicKeyCredentialDescriptorFuture[]
}) {
  const {
    rpID,
    rpName,
    userID,
    userName,
    authenticatorAttachment = 'platform',
    excludeCredentials,
    extensions,
  } = options;
  const _options: GenerateRegistrationOptionsOpts = {
    rpID,
    rpName,
    userID,
    userName,
    attestationType: 'none',
    authenticatorSelection: {
      authenticatorAttachment,
      residentKey: 'required',
      userVerification: 'required',
    },
    excludeCredentials,
  };

  return _generateRegistrationOptions(_options);
}
```

RP's using the current methods could migrate to these simpler new methods by updating just the import path since the method names would match, and then removing a few arguments to match the new APIs.

I welcome any feedback anyone might have about this proposal. I'll continue to play around with the idea because I think passkeys offer a unique opportunity to revisit some of the functionality of this library and try to get back to making WebAuthn simple to use. I fear all of the functionality that's been added to the core methods requires too much knowledge of WebAuthn to use, and I might have inadvertently betrayed my own goal 😂

**Comment by authcompanion** [comment]
Just brainstorming out loud, given `generateRegistrationOptions()` today can implement usernameless flow, one idea is to just double down on documentation for it. 

There is the one thread in discussions where you summarized it, but it takes some time rereading the thread multiple times (without intimate knowledge of the webauthn spec) to start to get an idea of how to implement usernameless. The documentation which would be geared to someone who is new to webauthn would be more valuable than a function with opinionated choices. 

Additionally, it might be interesting to consider taking yourself out of providing a reference RP implementation (and leave it to others) but instead provide like a "awesome webauthn/passkey" repo or page which aggregates RPs for others to reference. This would free up the precious time to focus solely on library and documentation. 

Just ideas of course. Thank you for the time and care you put into SimpleWebAuthn - means a lot to the community that follows you.

**Comment by MasterKale** [comment]
> Just brainstorming out loud, given `generateRegistrationOptions()` today can implement usernameless flow, one idea is to just double down on documentation for it.

Thank you for the suggestion! Your suggestion felt _right_, so I finally sat down and wrote out a page on Passkeys as a cheat sheet for options that should be specified when calling SimpleWebAuthn's methods. You can see a rendered version of the current draft here:

https://deploy-preview-18--compassionate-babbage-110122.netlify.app/docs/advanced/passkeys

I'd love everyone's feedback on this page, if it needs more detail, etc... I think I'm generally satisfied with it being something I'd personally pull up to consult real quick, but a fresh set of eyes would help me spot what might be too hand-wavey.
