### ISSUE TITLE
Remove node-fetch dependency after node.js upgrade > 18

### ISSUE THREAD

**Issue by korywka** [MasterKale/SimpleWebAuthn#270]
Just a reminder to drop `node-fetch`, node v18 supports native fetch.

https://nodejs.org/de/blog/announcements/v18-release-announce/#fetch-experimental

**Comment by MasterKale** [comment]
Thank you for calling this out. I don't know when I'll fully drop Node 16 support, though, so for now I'll continue to use node-fetch. Whenever it feels alright to drop Node 16 I'll look into switching to Node's functionality.
