### ISSUE TITLE
Question on "Test MakeCredential with RK"

### ISSUE THREAD

**Issue by dc-choi** [MasterKale/SimpleWebAuthn#271]
We are currently conducting an Interop Test using the SimpleWebAuthn library.

There was a problem while conducting the pre-test before the Interop Test, but there was a problem with 'rk'.

As a result of checking the official document, the description of rk is as follows.

```
This OPTIONAL property, known abstractly as the resident key credential property (i.e., client-side discoverable credential property),
is a Boolean value indicating whether the PublicKeyCredential returned as a result of a registration ceremony is a client-side discoverable credential.

If rk is true, the credential is a discoverable credential. if rk is false, the credential is a server-side credential.
If rk is not present, it is not known whether the credential is a discoverable credential or a server-side credential.
```

When I checked the above explanation, I confirmed that 'rk' follows 'residentKey', and it is called OPTIONAL property, but other places say that it must be passed.

When I checked the official document and applied the rk value, the test failed as follows.
![image](https://user-images.githubusercontent.com/57163578/190939218-b6853031-4865-42ac-9f61-84fa06468d64.png)

But without applying the rk value, the test is success.
![image](https://user-images.githubusercontent.com/57163578/190939280-7abc5820-b2a2-4d6a-a8a3-8b89249798b8.png)

What do you think of this problem at SimpleWebAuthn?

**Comment by MasterKale** [comment]
> This OPTIONAL property, known abstractly as the resident key credential property (i.e., client-side discoverable credential property), is a Boolean value indicating whether the PublicKeyCredential returned as a result of a registration ceremony is a client-side discoverable credential.
> 
> If rk is true, the credential is a discoverable credential. if rk is false, the credential is a server-side credential. If rk is not present, it is not known whether the credential is a discoverable credential or a server-side credential.

To clarify, this is a description of the [`rk` property in the `credProps` extension output](https://www.w3.org/TR/webauthn-2/#dom-credentialpropertiesoutput-rk). 

You can pass `{ credProps: true }` in as `extensions` to `navigator.credentials.create()`, **regardless of the value of `authenticatorSelection.residentKey` or `authenticatorSelection.requireResidentKey`**, and get back (from authenticators that support it) whether or not it generated a discoverable credential.



> What do you think of this problem at SimpleWebAuthn?

Can you provide code samples of how you're calling `generateRegistrationOptions()` when the tests fail, and then when they succeed? It'll also be helpful if you can copy-paste the error message(s) you're getting when the tests fails, the first screenshot cuts the errors off.

**Comment by dc-choi** [comment]
Currently, we have to return rk from FIDO Server.

The following is an example of the code we use.

```javascript
response = getServerSuccessResponse({
    ...result,
    credProtect,
    rk: authenticatorSelection.requireResidentKey,
    sessionId: session._id
});
```

Put the value of authenticatorSelection.requireResidentKey in rk as it is.

But if you change the value of rk to the next one, you pass the test

```javascript
response = getServerSuccessResponse({
    ...result,
    credProtect,
    rk: true,
    sessionId: session._id
});
```

Please contact me if you have any questions.

Thanks.

**Comment by MasterKale** [comment]
Neither `getServerSuccessResponse()` nor `getServerSuccessResponse()` are SimpleWebAuthn methods...how does that `rk` in your custom method's arguments affect how you ultimately call SimpleWebAuthn?

**Comment by MasterKale** [comment]
Please feel free to reopen this issue if you need further assistance.
