### ISSUE TITLE
WebKit support

### ISSUE THREAD

**Issue by Nwgazzazamwal** [MasterKale/SimpleWebAuthn#283]
hello, any idea if this is supported inside a webview react native

**Comment by MasterKale** [comment]
I haven't done any native iOS dev myself, but my current understanding is that you want to use [SFSafariViewController](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller) or [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) if you want to use passkeys in your native app.

The best advice I have for figuring out how to incorporate these into a React Native project, unfortunately, is to google "react native SFSafariViewController" or "react native ASWebAuthenticationSession". Good luck!

**Comment by MasterKale** [comment]
I'm going to turn this into a Discussion for now as it's not reporting an issue with SimpleWebAuthn.
