### ISSUE TITLE
Support for ES256K?

### ISSUE THREAD

**Issue by h4gen** [MasterKale/SimpleWebAuthn#288]
Hi all,

I am trying to use the ES256K curve for credential creation and verification. According to [CBOR](https://www.iana.org/assignments/cose/cose.xhtml) this should be fine but the process crashes when I try it.

This is the config I use:
```
  const options: PublicKeyCredentialCreationOptionsJSON = {
    challenge: "abcdef",
    attestation: "direct",
    pubKeyCredParams: [
      {
        alg: -47,
        type: "public-key",
      },
    ],
    rp: {
      //   id: "simplewebauthn.dev",
      name: "SimpleWebAuthn",
    },
    user: {
      id: "5678",
      displayName: "username",
      name: "username",
    },
    timeout: 1000,
    excludeCredentials: [
      {
        id: "C0VGlvYFratUdAV1iCw-ULpUW8E-exHPXQChBfyVeJZCMfjMFcwDmOFgoMUz39LoMtCJUBW8WPlLkGT6q8qTCg",
        type: "public-key",
        transports: ["internal"],
      },
    ],
  };
```

I realized that `pubKeyCredParams` has no `crv` parameter which should be `8` for ES256K with secp256k1. Can it be that this causes the error or is the`crv` implied with the `alg` choice? Or is it that the standard only defines that authenticators MUST implement ES256 and it just depends on the device?

Best,
Hagen

**Comment by MasterKale** [comment]
> ...but the process crashes when I try it.

Hello @h4gen, what do you mean here when you say, "the process?" Is the WebAuthn call immediately failing? Is your authenticator failing to respond with -47 as the old entry? Is the server library unable to verify the response?

If you can clarify that, and share a stack trace of whatever error you're getting, it'll go a long way in helping me help you.

**Comment by h4gen** [comment]
Hi @MasterKale,

thanks for the swift response! The error occurs directly when I try to generate the KeyPair. I am currently testing this locally on my laptop with several different browsers and just use Apple TouchID so far. The idea is that this should work via Touch or Face ID on Apple devices.

The key pair creation starts correctly:
![image](https://user-images.githubusercontent.com/12556763/194477817-7616731c-c4ad-4544-8c28-010272bbd8d7.png)

But afterwards I see this:
![image](https://user-images.githubusercontent.com/12556763/194478232-aab2d4b4-6c1c-4b8a-b475-84c1732f4a17.png)

So I fear Apple just does not support ES256K?

Best,
Hagen

**Comment by MasterKale** [comment]
Ah, alright, that's expected then. Apple's platform authenticators only support ES256 keypair generation (`-7`) so if you don't include that algorithm ID in `pubKeyCredParams` then you'll never be able to register a credential with them. `generateRegistrationOptions()` includes a bunch of different algorithms by default if you omit the `supportedAlgorithmIDs` argument when calling it:

https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/registration/generateRegistrationOptions.ts#L34-L55

But again, practically speaking I could narrow that list to `[-8, -7, -257]` for Ed22519, ES256, and RS256 respectively and support just about all common authenticators an RP using SimpleWebAuthn is likely to encounter.

**Comment by h4gen** [comment]
Okay, that explains it! Thank you so much for explaining and thank you for your great work with the library :)
