### ISSUE TITLE
How to add blob extension and use it for webauthn client?

### ISSUE THREAD

**Issue by djaffer** [MasterKale/SimpleWebAuthn#297]
I am wondering if I want to store user-relevant info how I can do it with the use of an extension? Is there an example?

**Comment by MasterKale** [comment]
@djaffer you can _try_ to use the [`largeBlob` extension](https://www.w3.org/TR/webauthn-2/#sctn-large-blob-extension), but honestly support for it is all but non-existent across the major browsers. At this moment in time there's nothing in the WebAuthn spec that I would advise anyone try to use for storing arbitrary data with a credential.
