### ISSUE TITLE
isCertRevoked cannot work for the root cert which does not include the Subject Key Identifier field

### ISSUE THREAD

**Issue by zkwzk** [MasterKale/SimpleWebAuthn#302]
Hello SimpleWebAuthn team,

Recently we are doing some spiking based on the SimpleWebAuthn, and we found that after we initialized the MetaDataService, the IDMelon(A software authenticator on iOS and Android) generated RegistrationOption cannot pass the MDS check, we did some investigation on the SimpleWebAuthn server library and found the isCertRevoked cannot work if the CA cert doesn't include the Subject Key Identifier, the right side is the root cert of the IDMelon we got from the FIDO2 MDS(AAGUID: `820D89ED-D65A-409E-85CB-F73F0578F82A`), which didn't include the Subject Key Identifier field, it only includes the Authority Key Identifier which does not have the kid field
![image (2)](https://user-images.githubusercontent.com/4729415/205802227-052f6ed7-c4c1-43d2-8084-43e42d462742.png)

we create a unit test to reproduce this issue, put it into (`verifyAttestationWithMetadata.test.ts`):
```
test('should verify attestation', async () => {
  const metadataStatement: MetadataStatement = {
    "legalHeader": "Submission of this statement and retrieval and use of this statement indicates acceptance of the appropriate agreement located at https://fidoalliance.org/metadata/metadata-legal-terms/.",
    "aaguid": "820d89ed-d65a-409e-85cb-f73f0578f82a",
    "description": "Vancosys iOS Authenticator",
    "authenticatorVersion": 2,
    "protocolFamily": "fido2",
    "schema": 3,
    "upv": [
      {
        "major": 1,
        "minor": 0
      }
    ],
    "authenticationAlgorithms": [
      "secp256r1_ecdsa_sha256_raw"
    ],
    "publicKeyAlgAndEncodings": [
      "cose"
    ],
    "attestationTypes": [
      "basic_full"
    ],
    "userVerificationDetails": [
      [
        {
          "userVerificationMethod": "faceprint_internal"
        },
        {
          "userVerificationMethod": "voiceprint_internal"
        },
        {
          "userVerificationMethod": "passcode_internal"
        },
        {
          "userVerificationMethod": "eyeprint_internal"
        },
        {
          "userVerificationMethod": "handprint_internal"
        },
        {
          "userVerificationMethod": "fingerprint_internal"
        },
        {
          "userVerificationMethod": "pattern_internal"
        },
        {
          "userVerificationMethod": "location_internal"
        },
        {
          "userVerificationMethod": "presence_internal"
        }
      ]
    ],
    "keyProtection": [
      "hardware",
      "secure_element"
    ],
    "matcherProtection": [
      "on_chip"
    ],
    "cryptoStrength": 128,
    "attachmentHint": [
      "external"
    ],
    "tcDisplay": [],
    "attestationRootCertificates": [
      "MIIB/zCCAaSgAwIBAgIUPbddlpEdAdN+fm8JFanUXurNZy8wCgYIKoZIzj0EAwIwQTEkMCIGA1UECgwbVmFuY29zeXMgRGF0YSBTZWN1cml0eSBJbmMuMRkwFwYDVQQDDBBWYW5jb3N5cyBSb290IENBMCAXDTIwMTEwNDA2NDQxN1oYDzIwNzAxMDIzMDY0NDE3WjBBMSQwIgYDVQQKDBtWYW5jb3N5cyBEYXRhIFNlY3VyaXR5IEluYy4xGTAXBgNVBAMMEFZhbmNvc3lzIFJvb3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARqViASimcpJwCb531/VekYHfNuRkIPeFkQq7FNyWkFiWPjKk1GDSAxJruB4GB3qdyTnRhpWF3Lvm4hzbBtZfy3o3gwdjBmBgNVHSMEXzBdoUWkQzBBMSQwIgYDVQQKDBtWYW5jb3N5cyBEYXRhIFNlY3VyaXR5IEluYy4xGTAXBgNVBAMMEFZhbmNvc3lzIFJvb3QgQ0GCFD23XZaRHQHTfn5vCRWp1F7qzWcvMAwGA1UdEwQFMAMBAf8wCgYIKoZIzj0EAwIDSQAwRgIhAOGjcwJUT7A/ER+5pACEPrOg79wbE/h8YMYUgymrXR6GAiEA7N6U3EWeQweMOmTOqavtWCdYCsMJcop9p13l9QbohDo="
    ],
    "icon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAM1BMVEUtmc3y+fyWzOZis9rK5fI6n9B8v+Cw2ezl8vlHptNVrNbX7Paj0ulvud293++JxuP///89HRvpAAAAEXRSTlP/////////////////////ACWtmWIAAABsSURBVHgBxdPBCoAwDIPh/yDise//tIIQCZo6RNGdtuWDstFSg/UOgMiADQBJ6J4iCwS4BgzBuEQHCoFa+mdM+qijsDMVhBfdoRFaAL4nAe6AeghODYPnsaNyLuAqg5AHwO9AYu5BmqEPhncFmecvM5KKQHMAAAAASUVORK5CYII=",
    "authenticatorGetInfo": {
      "versions": [
        "FIDO_2_0"
      ],
      "extensions": [
        "hmac-secret"
      ],
      "aaguid": "820d89edd65a409e85cbf73f0578f82a",
      "options": {
        "plat": false,
        "rk": true,
        "up": true,
        "uv": true
      },
      "maxMsgSize": 2048
    }
  };

  // Extracted from an actual TPM|ECC response
  const x5c = [
      'MIIB6TCCAY+gAwIBAgIJAJz56pzvu76hMAoGCCqGSM49BAMCMEExJDAiBgNVBAoMG1ZhbmNvc3lzIERhdGEgU2VjdXJpdHkgSW5jLjEZMBcGA1UEAwwQVmFuY29zeXMgUm9vdCBDQTAgFw0xODEyMjIxNzQzMjhaGA8yMDY4MTIwOTE3NDMyOFowfDELMAkGA1UEBhMCQ0ExJDAiBgNVBAoMG1ZhbmNvc3lzIERhdGEgU2VjdXJpdHkgSW5jLjEiMCAGA1UECwwZQXV0aGVudGljYXRvciBBdHRlc3RhdGlvbjEjMCEGA1UEAwwaVmFuY29zeXMgaU9TIEF1dGhlbnRpY2F0b3IwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATZVzbtmSJbzsoN6mfdD+t1LV52zB+LWN0UusmV9+sRmfNB49adqPQ+h0JOlEwfL4zkbMmuDr6JhBRKJ5/c0SkeozMwMTAMBgNVHRMBAf8EAjAAMCEGCysGAQQBguUcAQEEBBIEEIINie3WWkCehcv3PwV4+CowCgYIKoZIzj0EAwIDSAAwRQIgV7++U2fQyy6Qido7fDhsi5Grrt76LTgZ5XJlA9UKEVECIQDJO0YHevdU77VlZ+Of58oKMjWD3SkzC1SWSlhl3nezHQ=='
  ];
  const credentialPublicKey = 'pQECAyYgASFYINuJbeLdkZwgKtUw2VSopICTTO5PKdj95GXJ7JCsQi7iIlggxygEp0_P0oMXhfw2BjtL0M7-yIpnk5uSHc0oNkXfdJw';

  const verified = await verifyAttestationWithMetadata({
    statement: metadataStatement,
    credentialPublicKey: base64url.toBuffer(credentialPublicKey),
    x5c,
  });

  expect(verified).toEqual(true);
})
```
It will raise an error:
```
Error: Could not validate certificate path with any metadata root certificates: Cannot read properties of undefined (reading 'hex')
```

Thanks

**Comment by MasterKale** [comment]
Thank you for reporting this, @zkwzk. Is an X.509 certificate without an SKID a valid certificate? Seems like the real issue is that FIDO Metadata Service allowed a vendor to include a bad certificate...

I'm debating what to do here.

**Comment by zkwzk** [comment]
hello @MasterKale , thanks for the reply, according to the https://www.rfc-editor.org/rfc/rfc3280#section-4.2.1.2, the `keyIdentifier` in AuthorityKeyIdentifier can be an optional field, and it mentioned 
>  The identification MAY be based on either the key identifier (the subject key identifier in the issuer's certificate) or on the issuer name and serial number.

So I think it's a valid certificate

**Comment by MasterKale** [comment]
> The identification MAY be based on either the key identifier (the subject key identifier in the issuer's certificate) or on the issuer name and serial number.

This quote is actually from [Section 4.2.1.1](https://www.rfc-editor.org/rfc/rfc3280#section-4.2.1.1):

![Screenshot 2022-12-10 at 8 52 03 AM](https://user-images.githubusercontent.com/5166470/206866138-8eaefcef-698f-4576-b2f2-90f61330b7fa.png)

Looking at Section 4.2.1.2 more closely, this jumped out at me:

> To facilitate certification path construction, this extension MUST appear in all conforming CA certificates, that is, all certificates including the basic constraints extension ([section 4.2.1.10](https://www.rfc-editor.org/rfc/rfc3280#section-4.2.1.10)) where the value of cA is TRUE.  The value of the subject key identifier MUST be the value placed in the key identifier field of the Authority Key Identifier extension ([section 4.2.1.1](https://www.rfc-editor.org/rfc/rfc3280#section-4.2.1.1)) of certificates issued by the subject of this certificate.

I took another look at the Vancosys Root CA certificate on the right, and indeed we can see that `cA` has been marked true:

![205802227-052f6ed7-c4c1-43d2-8084-43e42d462742](https://user-images.githubusercontent.com/5166470/206866353-2276394a-2663-4f8b-bb8e-7695031647bb.png)

This makes me think that the certificate is indeed malformed, and that the fix here is to get an updated root certificate added to FIDO Metadata.

**Comment by MasterKale** [comment]
Found the issue, it's here where I try to read the Authority Key Identifier's Key ID:

https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/helpers/isCertRevoked.ts#L38

I think now we're talking about this part in Section 4.2.1.1:

> The keyIdentifier field of the authorityKeyIdentifier extension MUST be included in all certificates generated by conforming CAs to facilitate certification path construction.  There is one exception; where a CA distributes its public key in the form of a "self-signed" certificate, the authority key identifier MAY be omitted.  The signature on a self-signed certificate is generated with the private key associated with the certificate's subject public key.  (This proves that the issuer possesses both the public and private keys.) In this case, the subject and authority key identifiers would be identical, but only the subject key identifier is needed for certification path building.

That last sentence is interesting, it reads like this certificate would be valid if its Subject Key Identifier extension was present to provide a key ID. However I'm seeing that the root cert in question is missing a Subject Key Identifier...

```
{
  extAuthorityKeyIdentifier: {
    extname: 'authorityKeyIdentifier',
    issuer: {
      str: '/O=Vancosys Data Security Inc./CN=Vancosys Root CA',
      array: [Array]
    },
    sn: { hex: '3db75d96911d01d37e7e6f0915a9d45eeacd672f' }
  },
  extSubjectKeyIdentifier: undefined
}
```

So where would I get a public key ID to check this cert's revocation status?

**Comment by MasterKale** [comment]
I've posted about this root certificate issue in the fido-dev mailing list:

https://groups.google.com/a/fidoalliance.org/g/fido-dev/c/hhPYsFmhTaI

I believe that the FIDO Alliance should contact the IDMelon devs and request that they fix their root certificate issue in their authenticator metadata.

**Comment by zkwzk** [comment]
thanks @MasterKale for posting the issue to fido-dev mailing list, let's wait for the update

**Comment by MasterKale** [comment]
I worked with the fine folks over at IDmelon to generate a new root certificate that better-conforms to [RFC 5280](https://www.rfc-editor.org/rfc/rfc5280) (about X.509 certs). That should eventually appear in an updated FIDO MDS statement, though I have no ETA on that because I can't remember how long metadata refresh intervals are.

This issue also inspired me to make #310 with a slight tweak to certificate revocation check logic based on more nuanced understanding of the RFC above. It wouldn't have fixed this issue because the root cert itself had issues, but it should make the library generally more robust.

**Comment by MasterKale** [comment]
The IDmelon root cert has been confirmed updated in FIDO MDS:

https://groups.google.com/a/fidoalliance.org/g/fido-dev/c/hhPYsFmhTaI/m/uhn04zjIBwAJ

I've merged #310 but haven't yet released the new code. You should be able to refresh your metadata to get the new cert at least, though, so I don't think you'll have to wait for me to cut a new release.

**Comment by zkwzk** [comment]
thanks a lot @MasterKale, will check on my side and will update here later

**Comment by zkwzk** [comment]
already tried with the new IDMelon cert from the FIDO MDS, it works now, can close this issue, thanks @MasterKale again.
