### ISSUE TITLE
simplewebauthn(6.2.2), can't support firefox(107.0.1) 

### ISSUE THREAD

**Issue by cbingos** [MasterKale/SimpleWebAuthn#303]
in macos 13.0.1 , simplewebauthn(6.2.2), can't support firefox(107.0.1)

**Comment by MasterKale** [comment]
Hello @cbingos, this ticket is a little light on details. Are you requesting some kind of change to one of the libraries in this project?

**Comment by cbingos** [comment]
@MasterKale  There is no change, see the test address for details: https://zhouyipro.com/webauthn.html

**Comment by MasterKale** [comment]
Unfortunately Firefox on macOS has lacked FIDO2 support for quite some time: 

https://passkeys.dev/docs/reference/macos/#browser-behavior

The best way to handle this imo is do some browser+OS detection via User Agent parsing or via [`navigator.userAgentData`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData) and disable use of WebAuthn when you detect macOS Firefox.
