### ISSUE TITLE
Windows server2019 problem

### ISSUE THREAD

**Issue by iLonaKarpova** [MasterKale/SimpleWebAuthn#319]
I've wrote some simple project using SimpleWebAuthn that does registration and auth. It works great on localhost (running Windows 11), but fails when deployed at server env (running Windows Server 2019) with an error:
react_devtools_backend.js:4012 Error: Invalid key for curve: "Public key is not a point"
    at t.exports (async-vendor.js:91:329050)
    at t.exports (async-vendor.js:91:327623)
    at e.convertPublicKeyToPEM (async-vendor.js:91:326888)
    at e.verifySignature (async-vendor.js:73:28917)
    at e.verifyAuthenticationResponse (async-v
Could you please share any ideas what could be the reason?

**Comment by MasterKale** [comment]
Can you share more about how you're calling @simplewebauthn/server's methods? Code samples, ideally.

> async-vendor.js

Are you bundling **@simplewebauthn/server** into a front end project? It's not often you see vendoring like this in Node projects. If you are then that's part of the problem, Node is the only supported runtime for @simplewebauthn/server right now.

**Comment by iLonaKarpova** [comment]
Hello, Matthew.
Thank you for your response, you are right, I'm bundling server into a
front end project as a part of a demo project. I'll change it then. Thank
you very much.
Best regards,
iLona Karpova

**Comment by MasterKale** [comment]
If you're the adventurous type, the master branch currently has #299 in it which did a huge refactor to try and make it possible for **server** to run on more platforms. This includes using WebCrypto and Uint8Array everywhere, which means it's feasible to include server in a front end project as there's no longer going to be anything tightly coupling **server** to Node.

The catch is that you'd have to figure out how to get your project to work with CommonJS modules. I wouldn't spend a whole lot of time on that if you did decide to experiment with what will be released as SimpleWebAuthn v7.0.0 early next year, though, as in my experiments getting **server** running in a vite project I had to abandon CommonJS completely to get **server** running in the browser.

After v7.0.0 debuts I plan on taking another look at how I might make it possible for **server** to run in more browser-like environments, including browsers for those interested in building fully-contained demo sites. If you're interested I can tag you in a follow-up issue or discussion in the future when I have something for you to properly test with.

**Comment by iLonaKarpova** [comment]
Hello, Matthew.
Great plans! I'm very interested in your project cause it looks like future
of authentication, so please tag me. Also I talked to our system
administrator, he is certain that the project is working locally because
I'm logged as windows administrator and don't have special permissions set
up. I'm not sure why it influences key generation procedure, what can be
forbidden there. Perhaps I'll investigate in that direction while you are
preparing new release. Happy New Year and thank you again for your work and
help!
Have a good weekend,
iLona Karpova
