### ISSUE TITLE
Question: Use autofill before identifying users

### ISSUE THREAD

**Issue by Radiergummi** [MasterKale/SimpleWebAuthn#325]
I'm working on implementing SimpleWebAuthn for a new app I'm working on, and there's one thing I can't wrap my head around. The client side autofill UI requires authenticator options to determine which of its local keys the server will accept.  
The server, as implemented, requires the user ID however:
```typescript
app.get('/generate-authentication-options', (req, res) => {
  // You need to know the user by this point
  const user = inMemoryUserDeviceDB[loggedInUserId];
```
_(See [example/index.ts#L207-L209](https://github.com/MasterKale/SimpleWebAuthn/blob/3dec91f6fbdfba201e253436f07786a6ef7f99bf/example/index.ts#L207-L209))_

At this point, I'm trying to offer users to use their pass key instead of continuing with their email address - so I really _can't_ have them signed in already. How am I supposed to generate authentication options in that situation?

I suppose the example app is just a little convoluted, and remembers the user ID in global server state, so it will stick around after the registration is complete; unless apps have a single user, however, that approach won't work for real-life applications.  
I _think_ I'd need to pass the client options for autofill if no user ID was included in the request, and serve the full assertion challenge on subsequent requests including a user ID, but I'm not quite sure how to do that securely, or if I understood something fundamentally wrong.  
Do you have some advice?

**Comment by MasterKale** [comment]
As a matter of fact someone asked that same question earlier this week, take a look at this discussion and my response in it and let me know if it answers your question:

https://github.com/MasterKale/SimpleWebAuthn/discussions/321#discussioncomment-4551790

If it does, then I'll make this issue about _finally_ adding this guidance to the docs, so that more people might be able to discover them when implementing passkeys.

**Comment by MasterKale** [comment]
I added a new section to the Passkeys docs with suggestions on how to manage challenges during registration and authentication. Give it a look and let me know what you think:

https://simplewebauthn.dev/docs/advanced/passkeys/#remembering-challenges

**Comment by Radiergummi** [comment]
That's a splendid paragraph and explains things very well. This will surely help others in the future. Thank you very much for all your work, @MasterKale!
