### ISSUE TITLE
TypeError: Cannot destructure property 'id' of 'response' as it is undefined.

### ISSUE THREAD

**Issue by hckhanh** [MasterKale/SimpleWebAuthn#327]
I get this issue when I try to upgrade to v7

**Comment by MasterKale** [comment]
Please provide a basic recreation so I can see what's going wrong.

**Comment by hiDandelion** [comment]
> Please provide a basic recreation so I can see what's going wrong.

Hi. I encountered the same problem.

When inspect the response generated from `startRegistration()`, there is no 'id' in object 'response'. But somehow it seems `verifyRegistrationResponse()` is using it.

Here is an example of the response generated from `startRegistration()`.
```
{
  id: 'g8cOZ3b6PSSepgqXqkDR0P4KSdVMXqrwLT6H2e5N5Rk',
  rawId: 'g8cOZ3b6PSSepgqXqkDR0P4KSdVMXqrwLT6H2e5N5Rk',
  response: {
    attestationObject: 'o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVikSZYN5YgOjGh0NBcPZHZgW4_krrmihjLHmVzzuoMdl2NFAAAAAK3OAAI1vMYKZIsLJfHwVQMAIIPHDmd2-j0knqYKl6pA0dD-CknVTF6q8C0-h9nuTeUZpQECAyYgASFYIIa8J9okxM6WfH00pnW8hoH5RmolY0cHXbq6aPEnlSJpIlggao5v9yUaluDqS7sXDlvdOryqLWBQx_l0-U3VflHQ8NA',
    clientDataJSON: 'eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiVU56RHdlc083VkxMa1hndzhfbF84d1BJNS11Mnh3bks0aUFNc2xBMDVHZyIsIm9yaWdpbiI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImNyb3NzT3JpZ2luIjpmYWxzZX0',
    transports: [ 'internal' ]
  },
  type: 'public-key',
  clientExtensionResults: { credProps: { rk: true } },
  authenticatorAttachment: 'platform'
}

**Comment by MasterKale** [comment]
I no response yet so I assume you've figured it out. But for anyone else who comes across this issue, it sounds like there might be some confusion around the renaming of the `credential` method argument for `verifyRegistrationResponse()` and `verifyAuthenticationResponse()` I call out on the changelog:

> The `verifyAuthenticationResponse()` method has had its `credential` argument renamed to `response`

Nothing has changed about the "shape" of the value, you're still passing in the **entire** output from **@simplewebauthn/browser**'s `startRegistration()` or `startAuthentication()` (respectively). It's just the argument name that's changed.

This is the best advice I can give until someone can provide a full code example that causes this issue so I can see the methods and values you're using.

**Comment by hckhanh** [comment]
Thank you for your advice, i will take a look and try to make an example later. It's too busy recently
