### ISSUE TITLE
How best to store the publickey in a mysql database?

### ISSUE THREAD

**Issue by anthonywebb** [MasterKale/SimpleWebAuthn#334]
I am using 6.2.2 and it seems like all the examples I see out there just set up an object in memory and don't have to worry about converting these buffers into something that can be stored in the database.  And then retrieved and put back into a format that can be passed to verifyAuthenticationResponse()

I have tried this:
```zlib.gzipSync(JSON.stringify(the_publickey)).toString('base64')```

And then after pulling it from the DB (
```JSON.parse(zlib.unzipSync(Buffer.from(the_publickey, 'base64')))```

The above doesn't seem to be able to be then decoded very well by verifySignature.js, this line returns undefined:
```struct = cbor_1.default.decodeAllSync(credentialPublicKey)[0];```

So I am curious what everyone has found is the best way to store these buffers? And rehydrate them into something that can be passed to verifyAuthenticationResponse() successfully

**Comment by anthonywebb** [comment]
I found that all you need to do is declare the field a blob and read and write directly to/from it. No fancy encoding or decoding needed. 6.2.2 is working great for me now.

**Comment by MasterKale** [comment]
And if for some reason in the future you want to/can only store such values as a `string`-type value, I'd recommend a couple of paths.

## Pre-v7.0.0

Use a package like [`base64url`](https://www.npmjs.com/package/base64url) to convert `Buffer`'s to/from base64url strings.

## v7.0.0+

Use **@simplewebauthn/server**'s `isoBase64URL` helper to convert `Uint8Array`'s to/from base64url strings:

```ts
import { isoBase64URL } from '@simplewebauthn/server/helpers';

const verification = verifyRegistrationResponse(...);
const base64urlPubKey = isoBase64URL.fromBuffer(verification.registrationInfo.credentialPublicKey);
```
