### ISSUE TITLE
Allow to override supportedCOSEAlgorithmIdentifiers

### ISSUE THREAD

**Issue by mahnunchik** [MasterKale/SimpleWebAuthn#36]
It would be useful to be able to override `supportedCOSEAlgorithmIdentifiers` here: https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/attestation/generateAttestationOptions.ts#L85-L88

And here: https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/attestation/verifyAttestationResponse.ts#L141-L145

For example to support only `-7` ES256  and `-257` RS256.

**Comment by aseigler** [comment]
@MasterKale,  -65535 should not be included in supportedCOSEAlgorithmIdentifiers.  Allowing server side configuration for RP to only support certain algs makes sense but I would default to all supported.  I can't imagine why an RP would want to support only ES256 and RS256 but not ES512 or EdDSA for example, but it's acceptable.

**Comment by MasterKale** [comment]
@mahnunchik Not a problem, I've just pushed a new v0.7.2 that adds support for this (see PR #37)

**Comment by mahnunchik** [comment]
Hi @MasterKale I think it is incorrect to filter deprecated algorithm from provided by user options: https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/attestation/generateAttestationOptions.ts#L95-L100

If user really need specific algorithms it should be possible to specify any algorithms.

**Comment by mahnunchik** [comment]
@MasterKale let's discuss filtering of -65535

**Comment by MasterKale** [comment]
Okay, I'll admit I see the argument for letting implementers specify even deprecated algorithms when passing in their own list of supported values. I suppose it's painless to move the `.filter()` to the initialization of the default array of algorithms...

**Comment by MasterKale** [comment]
Alright, no ID's will be filtered out of custom arrays of ID's passed in as `supportedAlgorithmIDs` when calling `generateAttestationOptions()` 🎉 

This is fixed as of **@simplewebauthn/server v0.8.1**
