### ISSUE TITLE
Simplify example

### ISSUE THREAD

**Issue by mahnunchik** [MasterKale/SimpleWebAuthn#38]
It is possible to simplify example by removing SSL cert and key pair because browser treats requests to `localhost` at any port as secure connection in term of WebAuthn. https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API

**Comment by MasterKale** [comment]
Aha, you're right, I missed that "Secure Context" specifically includes `http://localhost` 🤦‍♂️ 

That said, while I _could_ remove the HTTPS setup for the example project, I'm going to leave it in. With one small change those same steps make it very easy to host the example at a custom subdomain that points to an internal IP to make the example accessible to other machines (Windows 10, Android/iOS devices, etc...). This simplifies the task of testing the spectrum of FIDO2-compliant authenticator hardware.

**Comment by mahnunchik** [comment]
I think it may be mentioned in the readme or in the code of example here: https://github.com/MasterKale/SimpleWebAuthn/blob/e9ef3215693225203920e39707cc6abeca25ae44/example/index.js#L271-L284

It makes it easy to launch a local example.
