### ISSUE TITLE
decodeAttestationObject.ts AttestationStatement type incompatible with early 4.x.x versions of Typescript

### ISSUE THREAD

**Issue by chunter301** [MasterKale/SimpleWebAuthn#395]
## Describe the issue

When using the latest version of @simplewebauthn/server 7.3.0 code fails to compile if using an early 4.x.x version of Typescript. The `get size(): number` getter on the AttestationStatement type causes errrors.

```
node_modules/@simplewebauthn/server/dist/helpers/decodeAttestationObject.d.ts:25:5 - error TS1131: Property or signature expected.

25     get size(): number;
       ~~~

node_modules/@simplewebauthn/server/dist/helpers/decodeAttestationObject.d.ts:25:9 - error TS1005: ';' expected.

25     get size(): number;
           ~~~~

node_modules/@simplewebauthn/server/dist/helpers/decodeAttestationObject.d.ts:25:15 - error TS1005: ';' expected.

25     get size(): number;
                 ~

node_modules/@simplewebauthn/server/dist/helpers/decodeAttestationObject.d.ts:26:1 - error TS1128: Declaration or statement expected.

26 };
   ~
```

## Reproduction Steps

1. Create a new Typescript project using version 4.0.7.
2. npm install the latest version of @simplewebauthn/server.
3. import and use a method from the library.
4. Compile the project.

## Expected behavior

The code will compile and run successfully.

## Potential Solution

After some testing the definition of the size getter could be switch to a simple size property and the implementation (whether getter or property) can be left up to the implementing object.

As an example of how this solves the issue here is a link to a minimal solution. https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwoF4oG8BQVtXgSwC8IAuKAOwFcBbAIwgCcBuDAXwwwGMAbAQ3nlgBGKHipguEKhDLABcROiw4A5hCT4iACgCUpSrQaKcxqPTUV6ZKIObG2bTr36wATCLESpMuQiSZjGtCoAMzMDhJIwMKoZBAA7kI6zBFQwG4x8a5JnAD2ZPA5EgB0XDnKmlFFgdrMHHkFxaXlaVWEEDUYQA

```ts
type Test = {
    size: number;
}

class T1 implements Test {
    get size(): number {
        return 1;
    }
}

class T2 implements Test {
    size = 3;
}

let t1 = new T1();
let t2 = new T2();
console.log(t1.size);
console.log(t2.size);
```

**Comment by MasterKale** [comment]
Thank you for reporting this @chunter-lumin, generalizing `size` like that seems like a reasonable thing to support projects stuck on older versions of TypeScript.

**Comment by chunter-lumin** [comment]
@MasterKale is there a process for me to create a PR for this change? It's seemingly a simple update so I would be willing to do the work. Or will I just need to wait for a future release? My organization is hoping to use this library and I would rather not try to use an older version if I don't need to.

**Comment by MasterKale** [comment]
Welcome to the world of open-source, and thank you for showing an interest in my library. If your company is interested in a support contract for timelier updates for things like this we can work something out. Alternatively consider sponsoring me here on GitHub - it's not required, but would be a nice gesture especially if you're generating revenue in something that incorporates my work:

https://github.com/sponsors/MasterKale

While you consider that, I see you joined GitHub "this month" (according to your profile anyway) - you might also use this as an opportunity to learn the ropes of FOSS contributions here in GitHub land. That involves learning how to fork a project's repo, make the changes you want to see in the project, and then submit a PR to the project.

**Comment by MasterKale** [comment]
I did some digging tonight and now I'm torn on making this change. **TypeScript 4.3** is the lowest version of the language that supports the `get size(): number` syntax that's raising the issue you reported. That's when TypeScript gained support for "Separate Write Types on Properties" was added:

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#separate-write-types-on-properties

TypeScript 4.3 came out in [May 2021](https://github.com/microsoft/TypeScript/releases/tag/v4.3.5). TypeScript 4.0 debuted [August 2020](https://github.com/microsoft/TypeScript/releases/tag/v4.0.2). I understand how difficult it can be to upgrade TypeScript versions on more established applications, but is there something preventing you from updating your project to use a newer version of TypeScript? If not all the way to the latest TypeScript 5 then to at least 4.3?

Another thing I'm not looking forward to solving right now is how to wire up CI tests to make sure I don't cause a regression in the future because I forget why I'm not using `get size(): number` for what is a read-only property at runtime. That's why I want to say "this project supports TypeScript 4.3+" and be done with this.

...I'm going to sleep on this and decide what to do tomorrow.

**Comment by chunter301** [comment]
Realistically, it is time for our projects to be updated to a newer version of Typescript as it's been about 2 years since our last update. A conversation partially stemming from this issue has started about upgrading to a newer version. From what I can tell simplewebauthn/server version 5.4.5 is the latest version that works with pre 4.3 Typescript, can you think of any concerns off the top of your head that using this version would cause?

**Comment by MasterKale** [comment]
> From what I can tell simplewebauthn/server version 5.4.5 is the latest version that works with pre 4.3 Typescript, can you think of any concerns off the top of your head that using this version would cause?

Using a version of this library from a year ago in a security-sensitive part of your product isn't something I'm going to officially condone. You're welcome to peruse the CHANGELOG for v5.4.5 and look at subsequent releases to see if anything in there might impact your security modeling:

https://github.com/MasterKale/SimpleWebAuthn/blob/master/CHANGELOG.md#v545

Put another way, sacrificing your project's ability to use the latest version of this library for the sake of your developer tooling (vis-a-vis the version of TypeScript your devs can build against) is probably not going to ever be worth it...

**Comment by MasterKale** [comment]
@chunter301 **@simplewebauthn/server@7.3.1** will allow you to kick that particular can down the road some with a tweak to the declaration of the `AttestationStatement.size` property. It's available now on NPM.

Please note that @simplewebauthn/server's minimum supported version of TypeScript is now version 4.4+. If your project remains stuck on TypeScript 4.0 and you still have issues, or if you wish to establish more timely support for future issues you encounter with SimpleWebAuthn, then please consider reaching out to establish a support contract with me.

**Comment by chunter301** [comment]
Thanks @MasterKale! Appreciate the quick responses.
