### ISSUE TITLE
Add rpID and origin used in the authenticationInfo and registrationInfo

### ISSUE THREAD

**Issue by Mikescops** [MasterKale/SimpleWebAuthn#414]
## Describe the proposal

During registration and authentication, metadata info are returned by the "verify" function.
I'd like to suggest to add the rpID and origin being used as the library accept an array of origin and rpID. 
This will be useful in order to let developers add custom logic or logging.

See here: 
- https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/registration/verifyRegistrationResponse.ts#L238
- https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/authentication/verifyAuthenticationResponse.ts#L211

**Comment by MasterKale** [comment]
This should be resolved in the newly-published **@simplewebauthn/server@7.4.0**. Thank you for your help in delivering this feature 🚀
