### ISSUE TITLE
Improve findability

### ISSUE THREAD

**Issue by mahnunchik** [MasterKale/SimpleWebAuthn#44]
It should make it easier to find the library:

* Add NPM keywords https://docs.npmjs.com/files/package.json#keywords
* Add Github topics https://github.blog/2017-01-31-introducing-topics/

At least `FIDO` and `WebAuthn` may be added 😉

**Comment by MasterKale** [comment]
NPM keywords are already taken care of:

<img width="503" alt="Screen Shot 2020-08-03 at 7 24 23 AM" src="https://user-images.githubusercontent.com/5166470/89193758-50a5ba00-d55b-11ea-9578-54bb0fc19852.png">

Now that the library is conformant I'll `FIDO` to these too. And **browser** may need a couple more too, now that I'm reviewing what it currently has.

As for Github topics, good call, I'll add some to the repo.

**Comment by MasterKale** [comment]
The repo now has some appropriate topics:

<img width="322" alt="Screen Shot 2020-08-03 at 8 19 58 AM" src="https://user-images.githubusercontent.com/5166470/89198502-299eb680-d562-11ea-9fdf-9a4b1e56f253.png">

I'll get `fido` added to the three packages in the next release, whenever that happens.

**Comment by mahnunchik** [comment]
Awesome 👍

**Comment by MasterKale** [comment]
The latest deployment of v0.8.2 included updated **npm** listing info with the new `fido` tag:

<img width="487" alt="Screen Shot 2020-08-11 at 10 44 36 PM" src="https://user-images.githubusercontent.com/5166470/89979316-4c952e80-dc24-11ea-84c4-361b3ed5bc40.png">
