### ISSUE TITLE
Inconsistent serviceName

### ISSUE THREAD

**Issue by mahnunchik** [MasterKale/SimpleWebAuthn#45]
Hi, it is small but breaking change.

It is inconsistent to have `serviceName` property name. It should be `rpName` by similarity with `rpID` and `user*` properties. Also `rpName` is close to specification.

I think it is ok to have that change for `1.0.0` release 😉

**Comment by MasterKale** [comment]
This issue has been fixed as of the newly-published [v0.9.0](https://github.com/MasterKale/SimpleWebAuthn/releases/tag/v0.9.0).
