### ISSUE TITLE
verifyRegistrationResponse() errors with "Insufficient data" 

### ISSUE THREAD

**Issue by Saif-Shines** [MasterKale/SimpleWebAuthn#462]
## Describe the issue

I am building a simple app to try web authn. During the registration, I followed I successfully generated registration options and passed them to verify them. Despite many efforts, always see verifyRegistrationResponse(..) returning `Error: Insufficient data`.

## Code Samples + WebAuthn Options and Responses

The following the JSON that clients sends to the server as part of verification:
```md
{
  id: "redacted", 
  rawId: "redacted",
  response: {
    attestationObject: "redacted",
    clientDataJSON: "redacted", 
    transports: ["hybrid", "internal"],
    publicKeyAlgorithm: -7, 
    publicKey: "redacted",
    authenticatorData: "redacted"
  },
  type: "public-key",
  clientExtensionResults: { 
    credProps: { rk: true }
  },
  authenticatorAttachment: "platform" 
}
```
Similarly, I do add all the options:
```js
try {
    const options = {
      credential: data,
      expectedChallenge: `${expectedChallenge}`,
      expectedOrigin: `${expectedOrigin}`,
      expectedRPID: rpID,
      requireUserVerification: true,
    };
    verification = await SimpleWebAuthnServer.verifyRegistrationResponse(
      options
    );
  } catch (error) {
    console.log("error during registration verification", error.message);
    return res.status(400).send({ error: error.toString() });
  }
```

The following is the error I always see:
```sh
error during registration verification 224 |       const parser = c._parse()
225 |       let state = parser.next()
226 |       while (!state.done) {
227 |         const b = s.read(state.value)
228 |         if ((b == null) || (b.length !== state.value)) {
229 |           throw new Error('Insufficient data')
                    ^
error: Insufficient data
      at decodeAllSync (/Users/saifas/Masters/coffeemasters-authn/node_modules/cbor/lib/decoder.js:229:16)
```
## Dependencies

- **OS:**  macOS 13.6
- **Browser:** https://www.whatsmybrowser.org/b/6QEL5
- **Authenticator:** Touch ID 

### SimpleWebAuthn Libraries

```sh
$ npm list --depth=0 | grep @simplewebauthn
├── @simplewebauthn/server@6.2.2
```

**Comment by MasterKale** [comment]
Hello @Saif-Shines, I notice you're using @simplewebauthn/server@6.2.2. The library has undergone extensive refactoring since November of last year. Please try updating to the latest **@simplewebauthn/server@8.2.3** and see if the issue still persists.

**Comment by MasterKale** [comment]
It's been three weeks with no follow-up so I'm closing this issue out.

**Comment by Saif-Shines** [comment]
Sorry for no follow up, @MasterKale — updating it to latest has solved the problem.
