### ISSUE TITLE
Example is broken with "User verification required, but user could not be verified"

### ISSUE THREAD

**Issue by damianobarbati** [MasterKale/SimpleWebAuthn#477]
## Describe the issue

Running the example (with the current instructions) results in the following:
<img width="2048" alt="Screenshot 2023-11-10 at 21 32 47" src="https://github.com/MasterKale/SimpleWebAuthn/assets/2225869/bceefe35-9423-476a-b2ee-34e1de58cabb">

**Comment by MasterKale** [comment]
Ah, thank you @damianobarbati, it seems at some point in the example I took out the user verification requirement from registration options but didn't make UV optional in registration response validation. I'll take care of this shortly.

If you don't want to wait you can either add `userVerification: 'required'` to `authenticatorSelection` ([here](https://github.com/MasterKale/SimpleWebAuthn/blob/master/example/index.ts#L144-L146)), or set `requireUserVerification: false` when verifying the response ([here](https://github.com/MasterKale/SimpleWebAuthn/blob/master/example/index.ts#L178)).

**Comment by MasterKale** [comment]
Thanks for your patience, I've gone ahead and updated the example! ✌️
