### ISSUE TITLE
No support for Bitwarden extension as an authenticator

### ISSUE THREAD

**Issue by smileservices** [MasterKale/SimpleWebAuthn#483]
Bitwarden is a chromium extension that can act as an authenticator. It's widely used and can replace the need for physical authenticators. passwordless.id has support for this, but SimpleWebAuthn does not. Any reason as to why this was left out and if it can be introduced?

**Comment by MasterKale** [comment]
Hello @smileservices, there's nothing about SimpleWebAuthn that is specific to any one authenticator. If an authenticator has implemented proper support for WebAuthn then it will work with SimpleWebAuthn.

That said, what kind of issue are you experiencing that gave you the impression that my libraries don't support BitWarden?

**Comment by smileservices** [comment]
Thanks for the quick response 🙏 I'm stumbling around playing with webauthn API on localhost. I didn't know how authenticator attachment impacts what type of authenticators are being used. Just discovered that chrome has a webauthn tool tab in dev tools. Seems like there's an issue on running this without https, but not sure. I'll close the issue.
