### ISSUE TITLE
Support other mediation options

### ISSUE THREAD

**Issue by mitar** [MasterKale/SimpleWebAuthn#489]
`startAuthentication` currently accepts the `PublicKeyCredentialRequestOptionsJSON` options and not the one level up options object (which would have `publicKey` as a field). This prevents one to pass `mediation` field alongside `publicKey`. There is a way to enable "conditional" mediation, but not for example "silent".

**Comment by MasterKale** [comment]
There's currently nothing in WebAuthn that leverages `"silent"` mediation with `publicKey` options, and nothing coming up that would use it either. I can't see right now what adding support for this type of mediation would enable.

I'm curious why you're trying to combine these. It's not a combination that anyone has ever proposed before, at least where I've been paying attention and participating.

**Comment by mitar** [comment]
I am just learning about webauth, so you are probably right that it might not make sense. I was primarily reading the spec and trying to see how does it look like in a browser if I specify silent mediation and I found out that I cannot specifying it using this library.
