### ISSUE TITLE
VerifiedRegistrationResponse type missing transports attribute

### ISSUE THREAD

**Issue by ladal1** [MasterKale/SimpleWebAuthn#491]
## Describe the issue

Based on documentation in [docs](https://simplewebauthn.dev/docs/packages/server#3-post-registration-responsibilities) `VerifiedRegistrationResponse` is supposed to have attribute transports, however typescript types do not contain such attribute

Using:
"@simplewebauthn/typescript-types": "8.3.4",
"@simplewebauthn/server": "8.3.5",

**Comment by MasterKale** [comment]
Thanks for raising this @ladal1, this is a simple case of the docs having fallen out of sync with the library. In v7.0.0 `transports` got moved one level deeper, into `response`, to more accurately mirror data structures defined in WebAuthn.

I'll leave this open as a reminder to update the docs accordingly.

**Comment by ladal1** [comment]
Yeah, I ended up using that by deduction myself, but wasn't sure if it's the documentation or the library, thanks 👍

**Comment by MasterKale** [comment]
I've updated the docs to pull transports from `body.request.transports` instead of the output of `verifyRegistrationResponse()` (I don't think they've ever been returned out of there 🤦):

https://simplewebauthn.dev/docs/packages/server#3-post-registration-responsibilities
