### ISSUE TITLE
RFC: Rename @simplewebauthn/typescript-types to something shorter

### ISSUE THREAD

**Issue by MasterKale** [MasterKale/SimpleWebAuthn#502]
## Describe the issue

"@simplewebauthn/typescript-types" is a mouthful of a package name. I am once again feeling the need to explore shortening this, to probably "**@simplewebauthn/types**". It's already implied that TypeScript is what the types are for, so including "typescript" in the package name has always been redundant.

If I decide to go through with this then I found out I can make the transition to the new package name easier by using `npm deprecate` to communicate the new name:

https://docs.npmjs.com/cli/v10/commands/npm-deprecate

I'll chew on this for a few days, and consider any feedback anyone might stop by with.

**Comment by lps88** [comment]
would make my package.json neat if it was `@types/simplewebauthn` :)

**Comment by MasterKale** [comment]
I went ahead with the package name change with #508. I also ran the following `npm` command to deprecate **@simplewebauthn/typescript-types** and point people to **simplewebauthn/types** instead:

```
npm deprecate @simplewebauthn/typescript-types "This package has been renamed to @simplewebauthn/types. Please install @simplewebauthn/types instead to ensure you receive future updates."
```

![Screenshot 2024-01-20 at 10 03 32 PM](https://github.com/MasterKale/SimpleWebAuthn/assets/5166470/002a1da1-cf81-4cee-ac81-3974e8da80cb)

**@simplewebauthn/typescript-types** will no longer shows up in searches on npmjs because of this:

![Screenshot 2024-01-20 at 10 03 45 PM](https://github.com/MasterKale/SimpleWebAuthn/assets/5166470/7e9f153d-cf32-4e9a-9d30-9f0db0fd182e)

The package rename is complete.

**Comment by MasterKale** [comment]
Docs site has been updated accordingly here:

https://github.com/MasterKale/SimpleWebAuthn-homepage/pull/43
