### ISSUE TITLE
Update minimum Node support to v20+

### ISSUE THREAD

**Issue by MasterKale** [MasterKale/SimpleWebAuthn#519]
## Describe the issue

**@simplewebauthn/server** still communicates official support for Node v16+, and currently tests against Node v16 and v18 in CI. Node v16 is EOL, though, and Node v18 entered its Maintenance back in January. Node v20 is the current Active LTS release.

I'm overdue to update the project's supported Node runtime to at least bump up minimum Node to v18, if not v20. Going with v20 would allow me to drop some of the hardest to support code in this project (I'm looking at you `getWebCrypto()`), but Node v18 is still in the game till April 2025 so it might be a little premature to drop it completely too.

In any case I need to update things here, and this issue will help me keep track of the requisite work.

**Comment by balazsorban44** [comment]
If you have a known user base, it might be interesting to know if you couldn't just recommend point 2 and 3 from this list: https://github.com/MasterKale/SimpleWebAuthn/issues/517#issue-2124165800

As an example there, even though Next.js supports v18, it makes sure the runtime has `crypto` exposed.

**Comment by MasterKale** [comment]
> If you have a known user base, it might be interesting to reach out to understand if you couldn't just recommend point 2 and 3 from this list: [#517 (comment)](https://github.com/MasterKale/SimpleWebAuthn/issues/517#issue-2124165800)
> 
> As an example there, even though Next.js supports v18, it makes sure the runtime has `globalThis.crypto` exposed already.

Thank you, I'll take this under consideration when I address this issue 🙌

**Comment by MasterKale** [comment]
This change is now available in the recently-published **@simplewebauthn/server@10.0.0** ✌️
