### ISSUE TITLE
Remove footgun related to random user IDs 

### ISSUE THREAD

**Issue by MasterKale** [MasterKale/SimpleWebAuthn#530]
## Describe the issue

Recent discussion over in the py_webauthn project (https://github.com/duo-labs/py_webauthn/issues/187) focused on how allowing strings for user IDs when generating registration options can encourage the use of PII since e.g. "emails are strings, so why not use that?" However, [the WebAuthn spec specifically discourages this pattern](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialuserentity-id) and encourages RPs to use random 64 bytes as IDs:

> The [user handle](https://www.w3.org/TR/webauthn-2/#user-handle) of the user account entity. A [user handle](https://www.w3.org/TR/webauthn-2/#user-handle) is an opaque [byte sequence](https://infra.spec.whatwg.org/#byte-sequence) with a maximum size of 64 bytes, and is not meant to be displayed to the user.

Additionally, in L3, new JSON serialization types have been defined that also say user.id should be a "Base64URLString" (an alias for DOMString but trying to communicate an encoding) when calling the upcoming PublicKeyCredential.parseCreationOptionsFromJSON() method:

https://w3c.github.io/webauthn/#dom-publickeycredentialuserentityjson-id

And the new PublicKeyCredential.toJSON() method will also base64url-encode userHandle bytes to make them JSON-friendly:

https://w3c.github.io/webauthn/#dom-publickeycredential-tojson

In this project, though, I treat `userID` and `userHandle` as UTF-8 strings because it'd been my belief that this was better developer experience to keep these values human-readable.

I think I need to give up my "developer experience" crusade here, though, as it runs counter to explicit user privacy goals in WebAuthn and just follow the spec more closely here.

To achieve this I should make similar behavior changes here that correspond to the ones I made to py_webauthn in https://github.com/duo-labs/py_webauthn/pull/197 and...

1. Make the `userID` argument in `generateRegistrationOptions()` an optional `Uint8Array`
2. When `userID` is not specified then generate 64 random bytes and return that (with instructions to RPs to associate these bytes with whatever user account the RP's site uses internally.)
3. Encode `userHandle` to base64url string instead in `startAuthentication()`

**Comment by spendres** [comment]
I am using them now for the userID. I suspect that they would fit within your proposed 64 byte Uint8Array type, but have not tested to determine if this would break my code.

Please consider using ULIDs for your userID generation given their benefits in data storage: [more info](https://github.com/oklog/ulid?tab=readme-ov-file)

**Comment by MasterKale** [comment]
I still think by default it's a good idea for me to generate completely random values when `userID` is omitted. However in your case there's nothing about what I'm proposing that would prevent you from using ULIDs for `userID`, so long as you figured out a way to convert them to a `Uint8Array` that you're comfortable with.

**Comment by rimu** [comment]
> so long as you figured out a way to convert them to a Uint8Array that you're comfortable with.

I have not...

I'm having some trouble with this - I let [py_webauthn](https://pypi.org/project/webauthn/) generate a user id from the backend (it gets encoded to "OPclcKTH6cjyjoRncpBrvKaepPz4eagbzFtOVnYCmANpUx0Vntm1lzlabOri5BF97CLNfTL440SIhbqwd459eQ") and then I'm [converting that to a Uint8Array](https://stackoverflow.com/a/70653061/635372) of 64 elements. But then startRegistration() has an exception "TypeError: User ID was not between 1 and 64 characters". 

Any tips?

**Comment by MasterKale** [comment]
> I'm having some trouble with this - I let [py_webauthn](https://pypi.org/project/webauthn/) generate a user id from the backend (it gets encoded to "OPclcKTH6cjyjoRncpBrvKaepPz4eagbzFtOVnYCmANpUx0Vntm1lzlabOri5BF97CLNfTL440SIhbqwd459eQ") and then I'm converting that to a Uint8Array

Are you feeding output from `generate_registration_options()` in **py_webauthn** to `startRegistration()` in **@simplewebauthn/browser**? If so you're intended to pass in the JSON options as-is and let `startRegistration()` take care of converting a value like `OPclcKTH6cjyjoRncpBrvKaepPz4eagbzFtOVnYCmANpUx0Vntm1lzlabOri5BF97CLNfTL440SIhbqwd459eQ` into the bytes that `navigator.credentials.create()` expects.

**Comment by rimu** [comment]
Ah, yes, now I can see where startRegistration does the conversion.

I was led down this path by your comment here https://github.com/duo-labs/py_webauthn/issues/199#issuecomment-1893114763. Is that no longer the case?

I'm using 9.0.1 which is a bit old. That is the version that ` <script src="https://unpkg.com/@simplewebauthn/browser/dist/bundle/index.umd.min.js"></script> ` provides. Would it help if I was using 9.0.3?

**Comment by rimu** [comment]
Solved by using a shorter user_id: https://github.com/duo-labs/py_webauthn/issues/199#issuecomment-1981888478

**Comment by MasterKale** [comment]
These changes are now available in the recently-published **@simplewebauthn/browser@10.0.0**, **@simplewebauthn/server@10.0.0**, and **@simplewebauthn/types@10.0.0** ✌️

**Comment by P4sca1** [comment]
@MasterKale Is it required to save the random generated user ID value in the database? From my understanding, it is randomly generated in `generateRegistrationOptions` but then it is never validated in the future. Do I miss something?
I previously used internal user ids (ascending integer ids) for the userId field, but I think I can just ignore the field entirely with v10? What is the value even for? Does it need to be known in the backend?

**Comment by wparad** [comment]
> @MasterKale Is it required to save the random generated user ID value in the database? From my understanding, it is randomly generated in `generateRegistrationOptions` but then it is never validated in the future. Do I miss something? I previously used internal user ids (ascending integer ids) for the userId field, but I think I can just ignore the field entirely with v10? What is the value even for? Does it need to be known in the backend?
@P4sca1, The userId is the userId, if you aren't using the userId how are you identifying who the user is?

**Comment by P4sca1** [comment]
> > @MasterKale Is it required to save the random generated user ID value in the database? From my understanding, it is randomly generated in `generateRegistrationOptions` but then it is never validated in the future. Do I miss something? I previously used internal user ids (ascending integer ids) for the userId field, but I think I can just ignore the field entirely with v10? What is the value even for? Does it need to be known in the backend?
> 
> @P4sca1, The userId is the userId, if you aren't using the userId how are you identifying who the user is?
I create a HTTP session when the authentication / registration process starts which contains the user id.
When verifying passkey authentication request, I select the Passkey with the given base64CredentialId. The resulting Passkey object contains the userId.

**Comment by P4sca1** [comment]
Okay, I found it in the spec (emphasis mine):
>A user handle is an identifier for a [user account](https://www.w3.org/TR/webauthn-3/#user-account), specified by the [Relying Party](https://www.w3.org/TR/webauthn-3/#relying-party) as [user](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialcreationoptions-user).[id](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialuserentity-id) during [registration](https://www.w3.org/TR/webauthn-3/#registration). [Discoverable credentials](https://www.w3.org/TR/webauthn-3/#discoverable-credential) store this identifier and MUST return it as [response](https://www.w3.org/TR/webauthn-3/#dom-publickeycredential-response).[userHandle](https://www.w3.org/TR/webauthn-3/#dom-authenticatorassertionresponse-userhandle) in [authentication ceremonies](https://www.w3.org/TR/webauthn-3/#authentication-ceremony) started with an [empty](https://infra.spec.whatwg.org/#list-empty) [allowCredentials](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialrequestoptions-allowcredentials) argument.
>
>**The main use of the [user handle](https://www.w3.org/TR/webauthn-3/#user-handle) is to identify the [user account](https://www.w3.org/TR/webauthn-3/#user-account) in such [authentication ceremonies](https://www.w3.org/TR/webauthn-3/#authentication-ceremony), but the [credential ID](https://www.w3.org/TR/webauthn-3/#credential-id) could be used instead.** The main differences are that the [credential ID](https://www.w3.org/TR/webauthn-3/#credential-id) is chosen by the [authenticator](https://www.w3.org/TR/webauthn-3/#authenticator) and is unique for each credential, while the [user handle](https://www.w3.org/TR/webauthn-3/#user-handle) is chosen by the [Relying Party](https://www.w3.org/TR/webauthn-3/#relying-party) and ought to be the same for all [credentials](https://www.w3.org/TR/credential-management-1/#concept-credential) registered to the same [user account](https://www.w3.org/TR/webauthn-3/#user-account).
>
>[Authenticators](https://www.w3.org/TR/webauthn-3/#authenticator) [map](https://www.w3.org/TR/webauthn-3/#authenticator-credentials-map) pairs of [RP ID](https://www.w3.org/TR/webauthn-3/#rp-id) and [user handle](https://www.w3.org/TR/webauthn-3/#user-handle) to [public key credential sources](https://www.w3.org/TR/webauthn-3/#public-key-credential-source). As a consequence, an authenticator will store at most one [discoverable credential](https://www.w3.org/TR/webauthn-3/#discoverable-credential) per [user handle](https://www.w3.org/TR/webauthn-3/#user-handle) per [Relying Party](https://www.w3.org/TR/webauthn-3/#relying-party). **Therefore a secondary use of the [user handle](https://www.w3.org/TR/webauthn-3/#user-handle) is to allow [authenticators](https://www.w3.org/TR/webauthn-3/#authenticator) to know when to replace an existing [discoverable credential](https://www.w3.org/TR/webauthn-3/#discoverable-credential) with a new one during the [registration ceremony](https://www.w3.org/TR/webauthn-3/#registration-ceremony).**

https://www.w3.org/TR/webauthn-3/#user-handle

For the secondary use case, it reads like the spec suggests to use the same user id for all authenticators that belong to the same user. This would imply that using random user ids is not ideal?

**Comment by P4sca1** [comment]
From https://www.w3.org/TR/webauthn-3/#sctn-user-handle-privacy:
> It is RECOMMENDED to let the [user handle](https://www.w3.org/TR/webauthn-3/#user-handle) be 64 random bytes, and store this value in the [user account](https://www.w3.org/TR/webauthn-3/#user-account).

=

**Comment by MasterKale** [comment]
(That said I still personally think it's okay to simply look up users by credential ID; I haven't heard of anyone running into issues with this approach. It's stuff like this that makes it hard to suggest the "best" way to do anything with SimpleWebAuthn: RP use cases and risk models are so varied I try to find a middle ground that'll not make a ton of work for any one type of RP...)

**Comment by P4sca1** [comment]
Thank you for the detailed answer and your continued work on the SimpleWebAuthn library!
I decided to continue using the user ids from database (incremental primary keys) as the user handle. They are not random and allow to identify a user within my application (at least find the associated username), but I do not consider this to be a privacy issue for my application. There is no email or real names revealed.
For authentication I continue looking up passkeys in my database based on the base64 credential id, instead of the user handle. This seems to be fine by the spec and is working fine. The user handle is not guaranteed to exist or exists in a different format for authenticators, that have been generated using previous registration options. The credential id is always there.

**Comment by MasterKale** [comment]
> The user handle is not guaranteed to exist or exists in a different format for authenticators, that have been generated using previous registration options. The credential id is always there.

This is another reason I started looking up users by credential ID and never really looked back. Nowadays `userHandle` is almost always being returned, but not even L3 is going to make `userHandle` required so as of 2024 RPs will still have to prepare to handle its absence. And when `userHandle` is unavailable, how else can you look up the user? By credential ID...such is the way this stuff goes 😂

**Comment by danielpizarro** [comment]
Reasons to use User Handle: https://github.com/w3c/webauthn/issues/1385#issuecomment-596420055
