### ISSUE TITLE
Discrepancy between example code and docs

### ISSUE THREAD

**Issue by RicardoE105** [MasterKale/SimpleWebAuthn#548]
## Describe the issue

On the example code, specifically when [verifying the authentication](https://github.com/MasterKale/SimpleWebAuthn/blob/master/example/index.ts#L286), the property `requireUserVerification` is set to true, but in the [docs](https://simplewebauthn.dev/docs/packages/server#2-verify-authentication-response), `requireUserVerification` it's not set. I'm using a Yubi Key, and the authentication only works when `requireUserVerification` is true during verification.  What am I missing?

**Comment by majdslmt** [comment]
I am trying to use this as server side with flutter app using https://pub.dev/packages/webauthn but the flutter app create payload register/verify like this {"authData":"dKbqkhPJnC90siSSsyDPQCYqlMGpUKA5fyklC2CEHvBFAAAAAAAAAAAAAAAAAAAAAAAAAAAAIApuetyDVhvSGAF7wJ_sJ6npdSb3PSuDkRUo-0Jd-taEpQECAyYgASFYIHDQhpLZ3q_4z5g6JvCdbsUFlhWRoAMmWBcBcuxVQ9JAIlggE9oA2sel6AqVSSCxl-uq62SOb64Gbc-MoUXX3cpYccE","fmt":"packed","attStmt":{"alg":-7,"sig":"MEYCIQDRxekD1zqdMn8Xu-eFSd3KIy78OJd77hR-jxeFs5304wIhAItP7JhcU36KDZ4Za7n3PrlzaYB-Iq8r-vYXfjTSMh2A"}} so i can use as a custom payload

**Comment by MasterKale** [comment]
> I'm using a Yubi Key, and the authentication only works when requireUserVerification is true during verification. What am I missing?

Hello @RicardoE105, what error are you getting when `requireUserVerification` is `false` or omitted? I'm not sure I understand what problem you're reporting, especially since you omitted the rest of the issue template that everyone is prompted to fill out when reporting issues like this one.

**Comment by MasterKale** [comment]
@majdslmt if you have an issue with this library please create a separate Issue. Otherwise if your question is about using this library to verify responses generated by a different library then please start a Discussion instead.

**Comment by MasterKale** [comment]
@RicardoE105 feel free to reopen this issue if you believe there's still an issue here.
