### ISSUE TITLE
Can't include browser package with webpack

### ISSUE THREAD

**Issue by nikashitsa** [MasterKale/SimpleWebAuthn#56]
My code:
```
const { SimpleWebAuthnBrowser } = require('@simplewebauthn/browser');
```
Error:
```
ERROR in ./node_modules/@simplewebauthn/browser/dist/simplewebauthn-browser.min.js
Module parse failed: Unexpected token (2:2177)
You may need an appropriate loader to handle this file type.
| // [@webauthentine/browser]  Version: 0.9.0 - Wednesday, September 9th, 2020, 11:12:48 PM  
```

Perhaps, webpack is old, but everything else works.
```
    "webpack-dev-server": "^2.8.1",
```

I think it's because of triple dots. Any ideas how to fix it?

**Comment by MasterKale** [comment]
Hmm, it looks like it's choking on the build version comment. That gets injected into the top of the file as a single-line comment, which is that last line in the error message.

I need more info about your setup - can you share as much as you can about your Webpack config? If you can strip things down to the bare essentials so I have something to run locally on my end I'll have a better chance at investigating a fix.

**Comment by nikashitsa** [comment]
I've deleted comment and get the same error. I think it's about because of this `...`  

Node: 12.14.1   
package.json
```
  "dependencies": {
    "@simplewebauthn/browser": "^0.9.0",
    "webpack-dev-server": "^2.8.1"
  }
```

webpack.config.js   
```
'use strict';

module.exports = {
  entry: {
    loader: ['./main.js'],
  }
};
```
main.js
```
const { SimpleWebAuthnBrowser } = require('@simplewebauthn/browser');
```

run script and get error above   
```
./node_modules/.bin/webpack-dev-server --config webpack.config.js
```

**Comment by MasterKale** [comment]
Hmm, if that's the case, do you have anything like `babel-loader` processing your JS files? I build the Browser package to target ES2018 environments and up. If **webpack-dev-server@2.8.1** isn't liking the spread syntax then you can probably address this with something that can transpile the lib down to whatever minimum target you're set up to target.

If you _do_ have Babel, perhaps this will help? https://babeljs.io/docs/en/babel-plugin-transform-spread

**Comment by nikashitsa** [comment]
Ok, thank you. Yes, this helped.
