### ISSUE TITLE
Parsing the attestation data explicitly

### ISSUE THREAD

**Issue by wparad** [MasterKale/SimpleWebAuthn#560]
We would like to easily parse the attestation data, but the library does not expose an explicitly method to do this. Right now that means we need to almost fake calling `verifyRegistrationResponse` again with the right inputs whenever we want this. It would be really great to have the method to parse the attestation data available on the exposed interface.

**Comment by MasterKale** [comment]
Check out `decodeAttestationObject()` and `parseAuthenticatorData()` exported from `@simplewebauthn/server/helpers`. Do either of those help you achieve your goals? There are many other helpers exported from there that you might find interesting too:

https://github.com/MasterKale/SimpleWebAuthn/blob/ba7048cfd791cd9400871d008d21d1354543e2b3/packages/server/src/helpers/index.ts#L17-L36

**Comment by MasterKale** [comment]
Thanks for the feedback @wparad. These helpers are used internally by the various option-generation and response-verification methods that represent the core methods of the **@simplewebauthn/server** package. I make them available via the `helpers` import for those who are intrepid enough to break out of the core WebAuthn use cases, so a bit of extra work should always be expected when using them.
