### ISSUE TITLE
The check for browser auto fill doesn't take into account shadow DOMs (ie: web components)

### ISSUE THREAD

**Issue by treeder** [MasterKale/SimpleWebAuthn#597]
The check here doesn't dive into the shadow DOM of web components so it won't see if there's an autocomplete input in a web component. 

https://github.com/MasterKale/SimpleWebAuthn/blob/a4a178cc8daa4eb5106b9708456195f3aff9643f/packages/browser/src/methods/startAuthentication.ts#L59

While this is supported in the major browsers now: https://issues.chromium.org/issues/40251770

**Comment by MasterKale** [comment]
Hello @treeder, it's unclear to me from that Chromium bug report what I might need to be doing differently here to support inputs within web components. I'm simply calling a DOM API, isn't it the browser's responsibility to make sure the shadow DOM gets checked too?

**Comment by treeder** [comment]
Shadow doms aren't exposed, that's kind of the point of them, they are isolated from everything else. I'm not sure of the answer to this, but I can play around next week and try to figure it out. Maybe the solution is to just not do this explicit check. 🤷‍♂️

**Comment by MasterKale** [comment]
The best solution I've been able to brainstorm so far is to add an option to `startAuthentication()` to ignore the DOM check so it won't error out 🤔

**Comment by treeder** [comment]
Ya, that's what I said in my previous comment. If that check isn't really essential then being able to bypass would be great.

**Comment by MasterKale** [comment]
> If that check isn't really essential then being able to bypass would be great.

Well, the check is accurate [as per the working draft of the L3 spec](https://w3c.github.io/webauthn/#GetAssn-ConditionalMediation-Interact-FormControl) that introduces conditional mediation:

> If options.[mediation](https://w3c.github.io/webappsec-credential-management/#dom-credentialrequestoptions-mediation) is [conditional](https://w3c.github.io/webappsec-credential-management/#dom-credentialmediationrequirement-conditional) and the user interacts with an [input](https://html.spec.whatwg.org/multipage/input.html#the-input-element) or [textarea](https://html.spec.whatwg.org/multipage/form-elements.html#the-textarea-element) form control with an [autocomplete](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete) attribute whose [non-autofill credential type](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#non-autofill-credential-type) is "webauthn",
>> Note: The "webauthn" [autofill detail token](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill-detail-tokens) must appear immediately after the last [autofill detail token](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill-detail-tokens) of type "Normal" or "Contact". For example:
>> - "username webauthn"
>> - "current-password webauthn"

So I'm inclined to keep the check in. I'm also at the point where if I add any more arguments to `startAuthentication()` then I'll switch from positional options to an options object. That'd necessarily break the method's API, which means **a major version release.**

(Just leaving some notes as I triage open issues.)

**Comment by treeder** [comment]
Isn't that spec for what the browser should do, not what your library should do? 

Not sure if this is useful, but here's an example from that chrome issue: https://nopwd.rocks/

**Comment by MasterKale** [comment]
@treeder Check out the new **@simplewebauthn/browser@11.0.0** - `startAuthentication()` gains a new `verifyBrowserAutofillInput` option that can be set to `false` to hopefully address your issue.

Just a heads up, the API of this method (and `startRegistration()`) changed to accept a single argument object, with the positional arguments as properties within. See the CHANGELOG for more info about this:

https://github.com/MasterKale/SimpleWebAuthn/blob/master/CHANGELOG.md#browser-positional-arguments-in-startregistration-and-startauthentication-have-been-replaced-by-a-single-object

**Comment by treeder** [comment]
I upgraded and looks like it works!

Here it is in action: https://thingster.app/login

Thanks!
