### ISSUE TITLE
Error: Cannot get schema for 'ECDSASigValue' target

### ISSUE THREAD

**Issue by mugambi40** [MasterKale/SimpleWebAuthn#608]
## Describe the issue

Am getting the Error: Cannot get schema for 'ECDSASigValue' target when I try to authentic.
I have implemented SimpleWebAuthn in a NextJs 14.2.8. Am using windows 11 to test.

## Dependencies

- **OS:** (Windows 11)
- **Browser:** (Edge Version 128.0.2739.79 (Official build) (64-bit))
- Node v20.17.0
- @simplewebauthn/browser: "^10.0.0",
- @simplewebauthn/server": "^10.0.1"

**Comment by MasterKale** [comment]
Hello @mugambi40 can you provide a minimal reproduction of the problem please? I can't help without at least a WebAuthn response that's causing this issue, but with NextJS in the mix it's hard to rule it out as part of the problem.

**Comment by mugambi40** [comment]
Hello @MasterKale the issue was in my code. I was able to fix.

**Comment by yuryharkavy** [comment]
> Hello [@MasterKale](https://github.com/MasterKale) the issue was in my code. I was able to fix.

Could you please share what was the issue? Currently I'm experiencing a similar one
