### ISSUE TITLE
`rpId` is not set in `PublicKeyCredentialRequestOptions`

### ISSUE THREAD

**Issue by agektmr** [MasterKale/SimpleWebAuthn#63]
There's no interface to pass `rpId` in `PublicKeyCredentialRequestOptions`.

**Comment by MasterKale** [comment]
Yikes, [you're right](https://www.w3.org/TR/webauthn-2/#dictionary-assertion-options). I'll work on adding this in.

**Comment by MasterKale** [comment]
I've just published **server@0.10.3** that adds a new `rpID` argument to `generateAssertionOptions()`. `rpID` maps to `rpId` as described in the WebAuthn spec (I stuck with "rpID" to match the argument name in `generateAttestationOptions()` since it can be the same value) ✌️
