### ISSUE TITLE
Android Timeout

### ISSUE THREAD

**Issue by Erseni** [MasterKale/SimpleWebAuthn#642]
## Describe the issue

On Android i can register with my fingerprint, but i cannot sign in. There is a Timeout and 

## Reproduction Steps

1. Go to https://webauthn.io/
2. Register your fingerprint
3. Click on Authenticate and there is a timeout Error
4. 
The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.
## Expected behavior

It should prompt for my fingerprint

## Code Samples + WebAuthn Options and Responses
Default Options on webauthn.io

## Dependencies

- **OS:** Galaxy S22+ Android 14
- **Browser:** latest Brave, latest Chrome
- **Authenticator:** Fingerprint or any other options

**Comment by MasterKale** [comment]
Hello @Erseni, are you reporting an issue with SimpleWebAuthn? This seems like an issue more appropriate to raise over in https://github.com/duo-labs/webauthn.io

**Comment by MasterKale** [comment]
Closing out for discussion over here:

https://github.com/duo-labs/webauthn.io/issues/146
