### ISSUE TITLE
Example Broken - FIDO Conformance

### ISSUE THREAD

**Issue by dmaesj** [MasterKale/SimpleWebAuthn#643]
## Reproduction Steps

1. Go through example tutorial
2. Enable FIDO_CONFORMANCE = true
3. Start server and see errors

## Expected behavior

Server should start with FIDO_CONFORMANCE = true and not throw errors

## Code Samples + WebAuthn Options and Responses

Refer to pull request submitted

## Dependencies

none

### SimpleWebAuthn Libraries

This is in regards to the example provided

## Additional context

Example is broken for FIDO Conformance

**Comment by MasterKale** [comment]
Thanks for the report @dmaesj, a fix has been merged with #644.
