### ISSUE TITLE
ReferenceError: generateChallenge is not defined with v12.0.0

### ISSUE THREAD

**Issue by semoal** [MasterKale/SimpleWebAuthn#648]
## Describe the issue

```bash
|- ReferenceError: generateChallenge is not defined
    at Function.assign (<anonymous>)
    at file:///Users/x/Projects/x/node_modules/.pnpm/@simplewebauthn+server@12.0.0_encoding@0.1.13/node_modules/@simplewebauthn/server/esm/helpers/index.js?iitm=true:6:18
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
```

## Reproduction Steps

I'll create a repro project later

## Expected behavior

With v11.0.0 the same code worked fine. 

## Dependencies

- **OS:** (e.g. macOS 13.2)
- **Node version**: v22.11.0
- **Browser:** (e.g. Chrome 110)
- **Authenticator:** (e.g. YubiKey 5, iPhone 12 @ iOS 16.3, 1Password browser extension 2.15.1)

### SimpleWebAuthn Libraries

```sh
$ npm list --depth=0 | grep @simplewebauthn
├── @simplewebauthn/browser@12.0.0
├── @simplewebauthn/server@12.0.0
# ...
```

**Comment by semoal** [comment]
Holy shit, after hours of debugging... it was sentry. Not sure what is doing under the hood, but literally broke the entire process, gonna open an issue there.

**Comment by MasterKale** [comment]
Hello @semoal, how did you fix this issue? I'm experiencing this same issue now while trying to diagnose #678, which involves a project using Sentry, and am wondering how you worked around this.

**Comment by kentcdodds** [comment]
More info here: https://github.com/getsentry/sentry-javascript/issues/12996
