### ISSUE TITLE
Build error when I tried to import SimpleWebAuthn server

### ISSUE THREAD

**Issue by PhuongLe** [MasterKale/SimpleWebAuthn#70]
Hi,
I am trying to import SimpleWebAuthn to my typescript project. After import it with npm, I got error as on the attached image.
```
npm install @simplewebauthn/server
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @simplewebauthn/server@0.10.3
added 32 packages from 28 contributors and audited 684 packages in 4.951s
found 179 vulnerabilities (123 low, 1 moderate, 54 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
phoebe@watsoncao-X570-UD:~/cybersec/clean-starter/app$ npm run build

> clean-starter@1.0.0 build /home/phoebe/cybersec/clean-starter/app
> tsc

node_modules/@types/pvutils/index.d.ts:115:42 - error TS2304: Cannot find name 'BufferSource'.

115     function arrayBufferToString(buffer: BufferSource): string;
                                             ~~~~~~~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! clean-starter@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the clean-starter@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/phoebe/.npm/_logs/2020-11-09T06_08_58_963Z-debug.log`
```

I just wonder if I did something wrong?

Thanks,

**Comment by MasterKale** [comment]
Hmm, interesting. `pvutils` is this library from the same people who make the ASN.1 parser library I use:

https://github.com/PeculiarVentures/pvutils

Why their types are erroring out, I'm not sure. Can you confirm your project's **TypeScript version**, and share your **tsconfig.json**?

**Comment by PhuongLe** [comment]
I am using Node 10.19.0, Tsc 3.8.3. You can see tsconfig.json [here](https://github.com/PhuongLe/clean-starter/blob/master/app/tsconfig.json)

**Comment by PhuongLe** [comment]
Do you have any idea? Which Node and TS version do you recommend?

**Comment by MasterKale** [comment]
No idea, this is a new one for me. I thought I documented a minimum Node version but I don't see it in the docs so I apologize. CI/CD tests against Node 12 and Node 14, though, as I consider 12 the minimum version of NodeJS that should be used with this (12 is dropping into maintenance mode at the end of this month, while 14 just became an LTS release) Can you try upgrading NodeJS to at least v12 and try again?

**Comment by PhuongLe** [comment]
yes, you are right. The error went away with latest Nodejs. Thank you, I will close this issue.

**Comment by PhuongLe** [comment]
FYI: I just realized that the error was not caused by Nodejs version. It is actually from the difference on tsconfig.json. I ignored the global variable from lib.dom.ts (es6) on tsconfig.json while lots of your code depends on this file.
