### ISSUE TITLE
Apple attestation

### ISSUE THREAD

**Issue by akanass** [MasterKale/SimpleWebAuthn#76]
A new attestation is existing now for [Apple device](https://w3c.github.io/webauthn/#sctn-apple-anonymous-attestation)

Maybe can solve some problems with TouchID / FaceID.

**Comment by akanass** [comment]
I didn't see the implementation inside the code and it's not listed in the README of the [server](https://github.com/MasterKale/SimpleWebAuthn/tree/master/packages/server#supported-attestation-formats)

So the implementation is done, sorry for this issue and you did a very good job :D

**Comment by MasterKale** [comment]
@akanass Thank you for noting that the server README didn't list `"apple"` attestation support - I've gone and updated that! It's now in-sync with the docs over on https://simplewebauthn.dev/ 😄
