### ISSUE TITLE
Feature proposal: Stateless Challenge via JWT

### ISSUE THREAD

**Issue by Moumouls** [MasterKale/SimpleWebAuthn#77]
![Capture d’écran 2020-12-04 à 10 10 41](https://user-images.githubusercontent.com/27959372/101144691-fefc6180-3618-11eb-887b-8b85ce7754e4.png)

For a better DX and also reinforced security (JWT allow to easly implement challenge expiration) it could be interesting to implement the following pattern

Main concept:
- Return a JWT signed version of the challenge with some user and options at the same time.

Pro: 
- Challenge not stored in DB
- Due to JWT expire behavior, challenge can expire
- On verify, call to DB can be avoided (since we can get userId from JWT)
- JWT secret can be rotated easly (through env vars, config, etc...)
- Better performance (reduce calls to DB)

Cons: 
- if an attacker can found the JWT secret he can spoof challenges (but in this case the challenge spoof would be the least of the developer's worries.  )
- Post other cons in comments

Lib could be used for this feature: https://www.npmjs.com/package/jsonwebtoken

**Comment by akanass** [comment]
Hi,

For my point of view, challenge isn't store in DB but in cache (memory) for a laps of time and it shouldn't transit in network for security reason, that's why he is staying in server side and if someone change the call to verify, it will failed.

**Comment by Moumouls** [comment]
@akanass 
`From my point of view, challenge isn't store in DB but in cache (memory) for a laps of time `
Here you have a major issue when you scale your server...

In production environment you need to at least store the challenge into a shared storage (redis/db etc...) currently

**Comment by akanass** [comment]
@Moumouls totally agree with you and in this case, `redis` is the best way to do it and not transferring challenge over network and deal only with content from I/O

**Comment by Moumouls** [comment]
@akanass stateless will be an additional/optional way to handle challenge, with a server signed challenge the challenge check is cryptographically safe into the backend 😉

**Comment by akanass** [comment]
@Moumouls I know what is `JWT` because I'm using it everyday :) but providing challenge like this it's not in the specification and should not be implemented from my point of view again.

**Comment by jstewmon** [comment]
To prevent replay attacks, the server would still need to store the unique id (e.g. `jti`) of the token during the register / authenticate request until it expires, regardless of whether the request succeeds of fails.

The point being that the server will incur the write IO operation for every sequence of requests anyway.

i.e. without using storage, you can't prevent replay, so moving the storage requirements from the first request to the second in the series doesn't seem like a compelling reason for the additional complexity of using a JWS vs an opaque challenge.

**Comment by Moumouls** [comment]
Here current draft: https://github.com/MasterKale/SimpleWebAuthn/pull/80/files

**Comment by akanass** [comment]
I am not ok with it even if the code seems fine :) https://github.com/MasterKale/SimpleWebAuthn/pull/80#pullrequestreview-545180323

**Comment by MasterKale** [comment]
In my opinion this feels like an WebAuthn implementation suggestion, and uncomfortably expands the scope of SimpleWebAuthn. Whether you use JWT's, Redis, etc... doesn't matter to SimpleWebAuthn - use what makes sense for your setup to transport the `challenge` that A) you provide to SimpleWebAuthn, or B) is generated by SimpleWebAuthn when you don't specify one.

This library is all about reducing the burden of understanding and implementing the WebAUthn spec - since the spec doesn't dictate how the challenge is transmitted from RP to client, the library doesn't either. For this reason I'm inclined to decline any contributions to this project that would try and make such an opinionated stance...
