### ISSUE TITLE
Passwordless: Possibility to skip allowCredentials

### ISSUE THREAD

**Issue by Moumouls** [MasterKale/SimpleWebAuthn#78]
In password less use case it's pretty hard to know in advance user ID. I remember that if we call navigator.credentials without allowCredentials, the browser can ask which Public Key the user wants to use (and display userName) if multiple public keys exists.

I saw that currently the lib require allowCredentials. Is there any security issue by allowing empty allowCredentials.

An alternative method could be to use localStorage to save the userId, but it need an additional front user selection system. I think it's also not safe since local storage can be cleared.

**Comment by akanass** [comment]
I agree with you @Moumouls and the [specification](https://w3c.github.io/webauthn/#dictionary-assertion-options) is ok with that.

**Comment by MasterKale** [comment]
Yeah, I think this is an alright suggestion too. I reviewed the spec myself this morning and debated on what "optional, defaulting to `[]`" really meant. However, I already allow `userVerification` to be optional and _it_ defaults to `"preferred"` so there's precedent for making `allowCredentials` optional as well.

I'll review #79 sometime in the next day or two and go from there.

**Comment by MasterKale** [comment]
PR #79 has been merged, but a release will have to wait till tonight.

**Comment by MasterKale** [comment]
`allowCredentials` is now optional as of the newly-released **@simplewebauthn/server@v0.10.5**, **@simplewebauthn/browser@v0.10.5**, and **@simplewebauthn/typescript-types@v0.10.5**
