### ISSUE TITLE
Interface for checking assertion flags

### ISSUE THREAD

**Issue by JayHelton** [MasterKale/SimpleWebAuthn#81]
Hello! I hope all is well! I was wondering if you could answer this question for me, i couldnt see anything explicit in the documentation.

I have found that not all browsers fully respect requiring user verification, examples being most major browsers on androids. Does SimpleWebAuthn support explicit checks for either the UV or the UP flag?

Something along the lines of 'assertionResponse.isUserVerified' or 'isUserPresenceVerified', etc, etc. Just to allow some additional control on how a server can response to settings of UV = required, but UV not being true in the response.

Thank you!

**Comment by akanass** [comment]
@JayHelton you can find your answer [here](https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/assertion/verifyAssertionResponse.ts#L131)

**Comment by MasterKale** [comment]
I responded via email but for posterity here was my response:

> I'm happy to point you to the `requireUserVerification` option in `verifyAttestationResponse()`:
> 
> https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/attestation/verifyAttestationResponse.ts#L41
> https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/attestation/verifyAttestationResponse.ts#L125
> 
> For assertion, there's the `fidoUserVerification` option in `verifyAssertionResponse()` that is a little more complex than a boolean, but to enforce UV = true you can set it to "required":
> 
> https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/assertion/verifyAssertionResponse.ts#L35
> https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/assertion/verifyAssertionResponse.ts#L127
