### ISSUE TITLE
Export some test utils

### ISSUE THREAD

**Issue by Moumouls** [MasterKale/SimpleWebAuthn#82]
For an easier server integration testing using this lib i think it could be helpful to export some assertion/attestation examples (output of startAssertion/startAttestation).
What do you think about that ?

**Comment by MasterKale** [comment]
That's an interesting proposal. This could involve moving the various sample attestations and assertions used in the various .test.ts files into a separate testing-oriented package 🤔

**Comment by Moumouls** [comment]
Yes testing package will be the right solution !
Here i only first think about the `server` integration testing part

But we can imagine later a plug and play testing util function for E2E front testing (ex: for cypress)
