### ISSUE TITLE
New release of specifications - Level 2

### ISSUE THREAD

**Issue by akanass** [MasterKale/SimpleWebAuthn#88]
A new release of the [specification](https://www.w3.org/TR/webauthn-2/) has been deployed and we should check it to be sure all is still conform to it.

**Comment by MasterKale** [comment]
Woo, L2 hit Candidate Release! One step closer to Recommendation!

If you're interested, you view a diff of L1 and the CR of L2 here: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2019%2FREC-webauthn-1-20190304%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2Fwebauthn-2%2F

This is where I admit that I've already implemented most of L2 in SimpleWebAuthn! I'll be going through that diff and comparing it to current SimpleWebAuthn functionality. If I notice anything off I'll capture it in here to prepare for a PR to get things updated.

**Comment by MasterKale** [comment]
## In-Progress Notes for L2 CR Updates:

- "Relying Parties SHOULD set [requireResidentKey] to `true` if, and only if, residentKey is set to `"required"`."
  - https://www.w3.org/TR/webauthn-2/#dom-authenticatorselectioncriteria-requireresidentkey

**Comment by MasterKale** [comment]
L2-specific changes addressed in PR #89 have been released as part of the latest **v1.0.0 release (🎉)**
