### ISSUE TITLE
default not exported

### ISSUE THREAD

**Issue by jkassis** [MasterKale/SimpleWebAuthn#93]
this is generated from my rollup...

'default' is not exported by apps/store/code/node_modules/@simplewebauthn/browser/dist/simplewebauthn-browser.min.js

thus ```import SimpleWebAuthnBrowser from '@simplewebauthn/browser'``` does not work

**Comment by jkassis** [comment]
also this...

```Error: 'supportsWebauthn' is not exported by apps/store/code/node_modules/@simplewebauthn/browser/dist/simplewebauthn-browser.min.js,```

**Comment by MasterKale** [comment]
@jkassis Can you provide some kind of basic setup that recreates this issue? I've not really used Rollup for anything significant so I have no idea why it's not liking the exports - a Webpack-based project (Create-React-App) is able to import the code fine so unfortunately no fix for Rollup comes to mind.

**Comment by MasterKale** [comment]
I'm going to close this for now. Please feel free to reopen if you can provide a reproduction I can use for further investigation.
