### ISSUE TITLE
How to use usernameless and passwordless at the same time

### ISSUE THREAD

**Issue by akanass** [MasterKale/SimpleWebAuthn#96]
As described in the [Yubico developer Guide](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/User_Handle.html) we can use `User Handle` to allow usernameless and passwordless authentication.

How to do it with this library and initiate `attestation` and `assertion` phases without a `username` because all documentation describes an associated user passed in parameter.

Thanks for your help.

**Comment by akanass** [comment]
I think I have my answer :)

If we don't give a `username` during `assertion phase` the client will ask the user which one he wants to use but to validate it correctly after, we have to store `User Handle` and use it like describe in the documentation.

This validation should be added inside `assertion verification phase` because for now only the `string` type is [checked](https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/assertion/verifyAssertionResponse.ts#L110) for this attribute.

And to store `User Handle` we have to ask the user to use the key ones before logout like a validation process because `User Handle` is not returned during `attestation verification phase`

**Comment by akanass** [comment]
https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Resident_Keys.html

**Comment by akanass** [comment]
If we want to authenticate a user with his `username` we have to set [residentKey](https://github.com/MasterKale/SimpleWebAuthn/blob/master/packages/server/src/attestation/generateAttestationOptions.ts#L128) to `required` as describe in the [specification](https://www.w3.org/TR/webauthn/#client-side-discoverable-credential)

Else, we have to ask him his `username`, retrieve authenticators associated to it, asking for user verification and then validating `User Handle` to be sure all is good

**Comment by MasterKale** [comment]
passwordless.dev is @aseigler's project and my goto for playing around with Passwordless and Usernameless. I took a look at attestation options and distilled the differences down to this:

## Passwordless
```json
{
  "user": {
    "name": "namehere",
    "id": "bmFtZWhlcmU",
    "displayName": null
  },
  "authenticatorSelection": {
    "requireResidentKey": false,
    "userVerification": "preferred"
  }
}
```

## Usernameless
```json
{
  "user": {
    "name": " (Usernameless user created at 2/1/2021 5:53:46 PM)",
    "id": "IChVc2VybmFtZWxlc3MgdXNlciBjcmVhdGVkIGF0IDIvMS8yMDIxIDU6NTM6NDYgUE0p",
    "displayName": null
  },
  "authenticatorSelection": {
    "requireResidentKey": true,
    "userVerification": "preferred"
  }
}
```

(I've omitted common stuff like RP info, challenge, etc...)

So yes, as you called out from the Yubico guide one difference is `requireResidentKey: true` (or the new `residentKey: "required"` in L2 of the WebAuthn spec).

I started a "Cookbooks" section for the SimpleWebAuthn docs to document this exact thing: a collection of options devs can specify to support either of these flows. I'll experiment with this in the next few days and restart that effort to document these collections of settings.

**Comment by akanass** [comment]
@MasterKale thanks for your answer.

For both, we have to store `User Handle` like this we can validate the user when is authenticated with username or not by finding the user in the database with the `User Handle` value.

That's why I'm asking you to add this field inside `AuthenticatorDevice` and validate it during `verification` phase.

**Comment by MasterKale** [comment]
Okay, after a few hours diving back into the spec I understand better now that for the sake of privacy `userHandle` (as `user.id` in attestation options) should always be a random 64-byte Buffer and never the user's actual internal DB ID.

This means that `generateAttestationOptions()` should be updated to generate that random `userHandle` every time and return it in attestation options. It'd then be the responsibility of the RP to take that userHandle, persist it until verification, then store it in the `credentials` table along with an fkey to the user's actual internal DB ID.

There's now additional load, outside of library functionality, to communicate all of this to people implementing this library who wish to take advantage of passwordless or usernameless flows...

> That's why I'm asking you to add this field inside AuthenticatorDevice and validate it during verification phase.

I understand your request better now, too, and this makes perfect sense. I'm going to model upcoming changes around [this diagram on this specific page in Yubico's dev guide](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Registering_Multiple_Devices.html):

![Screen Shot 2021-02-02 at 2 05 20 PM](https://user-images.githubusercontent.com/5166470/106668882-b51ff100-655f-11eb-918e-efd69b44f212.png)

**Comment by akanass** [comment]
Thanks @MasterKale and yes if we match the specific credentials data from Yubico I guess we are on the good way

**Comment by akanass** [comment]
UserHandle will allow us to find user in the database and the corresponding authenticator like this we can be sure that it was registered for this RP that's why we have to find AuthenticatorDevice inside the DB with UserHandle and validate all the fields save during attestation generation with the data received during attestation verification.

**Comment by MasterKale** [comment]
This issue is going to end up becoming a documentation issue, since PR #97 is adding additional return values from attestation that will be helpful in supporting passwordless and usernameless flows. Once that PR gets merged in work can begin on adding entries to the SimpleWebAuthn docs site containing "best practices" for setting up the RP to support these non-2FA WebAuthn flows.

**Comment by MasterKale** [comment]
I'm going to close this issue out for https://github.com/MasterKale/SimpleWebAuthn-homepage/issues/2.
